#!/usr/bin/env bats
# SPDX-License-Identifier: MIT
# Purpose: Tests for scripts/ci/check-semgrep-lock.sh (#2436)

load "../../helpers/common"

CI_SCRIPTS_DIR="${PROJECT_ROOT}/scripts/ci"

setup() {
	setup_temp_dir
	# A throwaway repo layout: the scripts derive the project root from their
	# own location, so copying them next to fixture requirements files keeps
	# the test off the real lockfile.
	REPO="${BATS_TEST_TMPDIR}/repo"
	mkdir -p "${REPO}/scripts/ci"
	cp "${CI_SCRIPTS_DIR}/check-semgrep-lock.sh" \
		"${CI_SCRIPTS_DIR}/compile-semgrep-lock.sh" \
		"${CI_SCRIPTS_DIR}/semgrep-lock-lib.sh" \
		"${REPO}/scripts/ci/"
	SCRIPT="${REPO}/scripts/ci/check-semgrep-lock.sh"

	printf 'semgrep==1.173.0\n' >"${REPO}/requirements-semgrep.in"

	# What the stubbed resolver will produce. The header names the output
	# path, exactly as uv writes it, so the test also covers the header
	# stripping that keeps a temp-file path out of the comparison.
	RESOLVED="${BATS_TEST_TMPDIR}/resolved.txt"
	cat >"${RESOLVED}" <<'EOF'
semgrep==1.173.0 \
    --hash=sha256:aaaa
attrs==26.1.0 \
    --hash=sha256:bbbb
    # via semgrep
EOF

	# PATH-shimmed uv: writes the canned resolution to --output-file and
	# stamps a header mentioning that path, without touching the network.
	# Like the real uv it reads an existing --output-file as resolution
	# preferences: a pin already present there is carried into the result.
	# That is what makes the gate's seeding step observable in these tests.
	BIN="${BATS_TEST_TMPDIR}/bin"
	mkdir -p "${BIN}"
	cat >"${BIN}/uv" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
output=""
while [[ $# -gt 0 ]]; do
	case "$1" in
	--output-file)
		output="$2"
		shift 2
		;;
	*) shift ;;
	esac
done
preferred=""
if [[ -f "${output}" ]]; then
	preferred="$(grep -E '^preference-marker==' "${output}" || true)"
fi
{
	echo "# This file was autogenerated by uv via the following command:"
	echo "#    uv pip compile --output-file ${output} requirements-semgrep.in"
	cat "${UV_STUB_RESOLVED}"
	if [[ -n "${preferred}" ]]; then
		printf '%s\n' "${preferred}"
	fi
} >"${output}"
EOF
	chmod +x "${BIN}/uv"
	export UV_STUB_RESOLVED="${RESOLVED}"
	export PATH="${BIN}:${PATH}"
}

teardown() {
	teardown_temp_dir
}

# Write a lockfile with a header naming its own path, as uv would.
write_lockfile() {
	local body="$1"
	{
		echo "# This file was autogenerated by uv via the following command:"
		echo "#    uv pip compile --output-file requirements-semgrep.txt requirements-semgrep.in"
		cat "${body}"
	} >"${REPO}/requirements-semgrep.txt"
}

@test "check-semgrep-lock.sh: --help exits 0" {
	run "$SCRIPT" --help
	assert_success
	assert_output --partial "Fail when the committed semgrep lockfile drifted"
}

@test "check-semgrep-lock.sh: passes when the lockfile matches the .in pin" {
	write_lockfile "${RESOLVED}"

	run "$SCRIPT"
	assert_success
	assert_output --partial "requirements-semgrep.txt is up to date"
}

@test "check-semgrep-lock.sh: header comments alone are not drift" {
	# Same resolved content, different generated header (a temp output path
	# and a different flag order) must still pass.
	{
		echo "# This file was autogenerated by uv via the following command:"
		echo "#    uv pip compile --generate-hashes --output-file /tmp/x/requirements-semgrep.txt requirements-semgrep.in"
		cat "${RESOLVED}"
	} >"${REPO}/requirements-semgrep.txt"

	run "$SCRIPT"
	assert_success
}

@test "check-semgrep-lock.sh: fails with the diff on a stale lockfile" {
	local stale="${BATS_TEST_TMPDIR}/stale.txt"
	sed 's/^semgrep==1.173.0/semgrep==1.170.0/' "${RESOLVED}" >"${stale}"
	write_lockfile "${stale}"

	run "$SCRIPT"
	assert_failure
	assert_equal "1" "$status"
	assert_output --partial "requirements-semgrep.txt is out of date"
	assert_output --partial "-semgrep==1.170.0"
	assert_output --partial "+semgrep==1.173.0"
	assert_output --partial "Run: scripts/ci/compile-semgrep-lock.sh"
}

@test "check-semgrep-lock.sh: seeds the committed lockfile as preferences" {
	# A pin the resolver only keeps when it can read the committed lockfile.
	# Without the seeding step in the gate the fresh resolution loses it and
	# the check reports drift on an otherwise untouched lockfile.
	local seeded="${BATS_TEST_TMPDIR}/seeded.txt"
	{
		cat "${RESOLVED}"
		echo "preference-marker==1.0.0"
	} >"${seeded}"
	write_lockfile "${seeded}"

	run "$SCRIPT"
	assert_success
	assert_output --partial "requirements-semgrep.txt is up to date"
}

@test "check-semgrep-lock.sh: fails when the lockfile is missing" {
	rm -f "${REPO}/requirements-semgrep.txt"

	run "$SCRIPT"
	assert_failure
	assert_output --partial "requirements-semgrep.txt not found"
	assert_output --partial "Run: scripts/ci/compile-semgrep-lock.sh"
}

@test "check-semgrep-lock.sh: fails when the .in pin is missing" {
	write_lockfile "${RESOLVED}"
	rm -f "${REPO}/requirements-semgrep.in"

	run "$SCRIPT"
	assert_failure
	assert_output --partial "requirements-semgrep.in not found"
}

@test "check-semgrep-lock.sh: fails closed when uv is absent" {
	write_lockfile "${RESOLVED}"
	local stub_path
	stub_path="$(make_stub_path "${BATS_TEST_TMPDIR}/nouv" bash cat command cp diff dirname grep mktemp pwd rm sed)"

	PATH="${stub_path}" run "$SCRIPT"
	assert_failure
	assert_output --partial "uv is required"
}

@test "semgrep-lock-lib.sh: executing the library only prints help" {
	run "${REPO}/scripts/ci/semgrep-lock-lib.sh" --help
	assert_success
	assert_output --partial "This file is a library"
}

@test "compile-semgrep-lock.sh: rewrites the lockfile through the shared helper" {
	write_lockfile "${RESOLVED}"
	printf 'semgrep==1.174.0\n' >"${REPO}/requirements-semgrep.in"
	sed 's/^semgrep==1.173.0/semgrep==1.174.0/' "${RESOLVED}" >"${RESOLVED}.next"
	UV_STUB_RESOLVED="${RESOLVED}.next" run "${REPO}/scripts/ci/compile-semgrep-lock.sh"
	assert_success

	run grep -c 'semgrep==1.174.0' "${REPO}/requirements-semgrep.txt"
	assert_success

	# The gate agrees with what the compile script just wrote.
	UV_STUB_RESOLVED="${RESOLVED}.next" run "$SCRIPT"
	assert_success
}
