"""Init command for Lintro project onboarding.

Detects project languages, generates `.lintro-config.yaml`, and recommends
install profiles and next steps.

Usage:
    lintro init
    lintro init --minimal
    lintro init --force
"""

from __future__ import annotations

import json
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel

from lintro.cli_utils.onboarding import print_install_next_steps
from lintro.tools.core.tool_registry import ToolRegistry
from lintro.utils.project_detection import detect_project_languages

# Static templates retained for tests and --static mode
DEFAULT_CONFIG_TEMPLATE = """\
# Lintro Configuration
# https://github.com/lgtm-hq/py-lintro

enforce:
  line_length: 88
  target_python: "py313"

execution:
  enabled_tools: []
  tool_order: priority
  fail_fast: false

defaults:
  mypy:
    strict: true
    ignore_missing_imports: true

tools:
  ruff:
    enabled: true
  black:
    enabled: true
  mypy:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  bandit:
    enabled: true
  hadolint:
    enabled: true
  actionlint:
    enabled: true
"""

MINIMAL_CONFIG_TEMPLATE = """\
# Lintro Configuration (Minimal)
# https://github.com/lgtm-hq/py-lintro

enforce:
  line_length: 88
  target_python: "py313"

defaults:
  mypy:
    strict: true
    ignore_missing_imports: true

execution:
  tool_order: priority

tools:
  ruff:
    enabled: true
  black:
    enabled: true
  mypy:
    enabled: true
"""


def _write_file(
    path: Path,
    content: str,
    console: Console,
    *,
    force: bool,
) -> bool:
    """Write content to a file, handling existing files."""
    if path.exists() and not force:
        console.print(f"  [yellow]Skipped {path} (already exists)[/yellow]")
        return False

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        console.print(f"  [green]Created {path}[/green]")
        return True
    except OSError as exc:
        console.print(f"  [red]Failed to write {path}: {exc}[/red]")
        return False


def _generate_config(
    tools: list[str],
    detected_langs: list[str],
    *,
    minimal: bool,
) -> str:
    """Generate .lintro-config.yaml content for the given tools."""
    lines = [
        "# Lintro configuration — generated by 'lintro init'",
        "# https://github.com/lgtm-hq/py-lintro/tree/main/docs",
        "",
    ]
    if detected_langs:
        langs = ", ".join(detected_langs)
        lines.append(f"# Detected languages: {langs}")
        lines.append("")

    if "python" in detected_langs and not minimal:
        lines.extend(
            [
                "enforce:",
                "  line_length: 88",
                "  target_python: py313",
                "",
            ],
        )
    else:
        lines.append("enforce:")
        lines.append("  line_length: 88")
        lines.append("")

    lines.extend(
        [
            "execution:",
            f"  enabled_tools: [{', '.join(sorted(tools))}]",
            "  tool_order: priority",
            "  fail_fast: false",
            "",
            "tools:",
        ],
    )
    for tool_name in sorted(tools):
        lines.append(f"  {tool_name}:")
        lines.append("    enabled: true")
    lines.append("")
    return "\n".join(lines)


def _generate_native_configs(console: Console, *, force: bool) -> list[str]:
    """Generate optional native tool configuration files."""
    created: list[str] = []
    template = {
        "config": {
            "MD013": {
                "line_length": 88,
                "code_blocks": False,
                "tables": False,
            },
        },
    }
    path = Path(".markdownlint-cli2.jsonc")
    if _write_file(
        path,
        json.dumps(template, indent=2) + "\n",
        console,
        force=force,
    ):
        created.append(str(path))
    return created


@click.command("init")
@click.option(
    "--minimal",
    "-m",
    is_flag=True,
    help="Create a minimal config with fewer defaults.",
)
@click.option(
    "--force",
    "-f",
    is_flag=True,
    help="Overwrite existing configuration files.",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default=".lintro-config.yaml",
    help="Output file path (default: .lintro-config.yaml).",
)
@click.option(
    "--with-native-configs",
    is_flag=True,
    help="Also generate native tool configs (.markdownlint-cli2.jsonc).",
)
@click.option(
    "--profile",
    type=str,
    default=None,
    help="Install profile to resolve tools (default: recommended).",
)
@click.option(
    "--static",
    is_flag=True,
    help="Use built-in static templates instead of language detection.",
)
def init_command(
    minimal: bool,
    force: bool,
    output: str,
    with_native_configs: bool,
    profile: str | None,
    static: bool,
) -> None:
    """Initialize Lintro configuration for your project.

    Detects languages, enables appropriate tools in config, and prints
    next steps for installing tools and running checks.

    Args:
        minimal: Use minimal template with fewer defaults.
        force: Overwrite existing config file if it exists.
        output: Output file path for the config file.
        with_native_configs: Also generate native tool config files.
        profile: Profile used to select tools for enabled_tools.
        static: Use static templates instead of detection.

    Raises:
        SystemExit: If file exists and --force not provided, or write fails.
        click.UsageError: If the selected profile does not exist.
    """
    console = Console()
    output_path = Path(output)

    if output_path.exists() and not force:
        console.print(
            f"[red]Error: {output_path} already exists. "
            "Use --force to overwrite.[/red]",
        )
        raise SystemExit(1)

    if static:
        config_content = MINIMAL_CONFIG_TEMPLATE if minimal else DEFAULT_CONFIG_TEMPLATE
        tool_names: list[str] = []
        detected_langs: list[str] = []
    else:
        registry = ToolRegistry.load()
        detected_langs = detect_project_languages()
        effective_profile = profile or ("minimal" if minimal else "recommended")

        if effective_profile not in registry.profile_names:
            raise click.UsageError(
                f"Unknown profile {effective_profile!r}. "
                f"Available: {', '.join(registry.profile_names)}",
            )

        tool_list = registry.tools_for_profile(
            effective_profile,
            detected_langs if detected_langs else None,
        )
        tool_names = [t.name for t in tool_list]
        config_content = _generate_config(
            tool_names,
            detected_langs,
            minimal=minimal,
        )

    try:
        output_path.write_text(config_content, encoding="utf-8")
    except OSError as exc:
        console.print(f"[red]Error: Failed to write {output_path}: {exc}[/red]")
        raise SystemExit(1) from exc

    created_files = [str(output_path)]
    if with_native_configs:
        created_files.extend(_generate_native_configs(console, force=force))

    console.print()
    if len(created_files) == 1:
        console.print(
            Panel.fit(
                f"[bold green]Created {output_path}[/bold green] "
                f"with {len(tool_names)} tools",
                border_style="green",
            ),
        )
    else:
        files_list = "\n".join(f"  • {f}" for f in created_files)
        console.print(
            Panel.fit(
                f"[bold green]Created {len(created_files)} files:[/bold green]\n"
                f"{files_list}",
                border_style="green",
            ),
        )

    if not static:
        effective_profile = profile or ("minimal" if minimal else "recommended")
        if detected_langs:
            console.print(
                f"  [dim]Detected: {', '.join(detected_langs)} | "
                f"Profile: {effective_profile}[/dim]",
            )
        console.print()
        console.print("  [bold]Recommended:[/bold]")
        console.print(
            f"    lintro install --profile {effective_profile}   "
            "[dim]Install tools for this project[/dim]",
        )
    else:
        console.print()
        console.print("[bold cyan]Next steps:[/bold cyan]")
        console.print("  [dim]1.[/dim] Review and customize the configuration")
        console.print("  [dim]2.[/dim] Run [cyan]lintro config[/cyan] to view config")
        console.print("  [dim]3.[/dim] Run [cyan]lintro check .[/cyan] to lint")
    if not static:
        print_install_next_steps(console)
