"""Init command for Lintro project onboarding.

Detects project languages, generates `.lintro-config.yaml`, and recommends
install profiles and next steps.

Usage:
    lintro init
    lintro init --minimal
    lintro init --force
"""

from __future__ import annotations

import json
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel

from lintro.cli_utils.onboarding import print_install_next_steps
from lintro.tools.core.tool_registry import ManifestRegistry
from lintro.utils.project_detection import detect_project_languages

# Static templates retained for tests and --static mode
DEFAULT_CONFIG_TEMPLATE = """\
# Lintro Configuration
# https://github.com/lgtm-hq/py-lintro

enforce:
  line_length: 88
  target_python: "py313"

execution:
  enabled_tools: []
  tool_order: priority
  fail_fast: false

defaults:
  mypy:
    strict: true
    ignore_missing_imports: true

tools:
  ruff:
    enabled: true
  black:
    enabled: true
  mypy:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  bandit:
    enabled: true
  hadolint:
    enabled: true
  actionlint:
    enabled: true
"""

MINIMAL_CONFIG_TEMPLATE = """\
# Lintro Configuration (Minimal)
# https://github.com/lgtm-hq/py-lintro

enforce:
  line_length: 88
  target_python: "py313"

defaults:
  mypy:
    strict: true
    ignore_missing_imports: true

execution:
  tool_order: priority

tools:
  ruff:
    enabled: true
  black:
    enabled: true
  mypy:
    enabled: true
"""


def _extract_tool_names(config_content: str) -> list[str]:
    """Extract tool names from a YAML config template without importing PyYAML.

    Looks for lines under a top-level ``tools:`` key that match the pattern
    ``  <name>:`` (two-space indent, no further nesting).

    Args:
        config_content: Raw YAML config string.

    Returns:
        List of tool names found.
    """
    import re

    names: list[str] = []
    in_tools = False
    for line in config_content.splitlines():
        if re.match(r"^tools:\s*$", line):
            in_tools = True
            continue
        if in_tools:
            m = re.match(r"^  (\w[\w-]*):", line)
            if m:
                names.append(m.group(1))
            elif line and not line.startswith(" "):
                break
    return names


def _write_file(
    path: Path,
    content: str,
    console: Console,
    *,
    force: bool,
) -> bool:
    """Write content to a file, handling existing files."""
    if path.exists() and not force:
        console.print(f"  [yellow]Skipped {path} (already exists)[/yellow]")
        return False

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        console.print(f"  [green]Created {path}[/green]")
        return True
    except OSError as exc:
        console.print(f"  [red]Failed to write {path}: {exc}[/red]")
        return False


def _generate_config(
    tools: list[str],
    detected_langs: list[str],
    *,
    minimal: bool,
) -> str:
    """Generate .lintro-config.yaml content for the given tools."""
    lines = [
        "# Lintro configuration — generated by 'lintro init'",
        "# https://github.com/lgtm-hq/py-lintro/tree/main/docs",
        "",
    ]
    if detected_langs:
        langs = ", ".join(detected_langs)
        lines.append(f"# Detected languages: {langs}")
        lines.append("")

    if "python" in detected_langs and not minimal:
        lines.extend(
            [
                "enforce:",
                "  line_length: 88",
                "  target_python: py313",
                "",
            ],
        )
    else:
        lines.append("enforce:")
        lines.append("  line_length: 88")
        lines.append("")

    lines.extend(
        [
            "execution:",
            f"  enabled_tools: [{', '.join(sorted(tools))}]",
            "  tool_order: priority",
            "  fail_fast: false",
            "",
            "tools:",
        ],
    )
    for tool_name in sorted(tools):
        lines.append(f"  {tool_name}:")
        lines.append("    enabled: true")
    lines.append("")
    return "\n".join(lines)


def _merge_config(
    path: Path,
    new_content: str,
    console: Console,
) -> str | None:
    """Merge generated config into an existing file.

    Preserves user-managed keys; only updates ``tools`` entries and
    ``execution.enabled_tools`` that Lintro owns. Returns the merged
    content, or None if nothing changed.
    """
    try:
        import yaml
    except ImportError:
        console.print(
            f"  [yellow]{path} exists; install PyYAML to merge, "
            "or use --force to overwrite.[/yellow]",
        )
        raise SystemExit(1)  # noqa: B904

    try:
        existing_raw = path.read_text(encoding="utf-8")
        existing = yaml.safe_load(existing_raw)
    except (OSError, yaml.YAMLError) as exc:
        console.print(
            f"  [yellow]Could not parse {path}: {exc}; "
            "use --force to overwrite.[/yellow]",
        )
        raise SystemExit(1) from exc

    if not isinstance(existing, dict):
        console.print(
            f"  [yellow]{path} is not a YAML mapping; "
            "use --force to overwrite.[/yellow]",
        )
        raise SystemExit(1)

    new = yaml.safe_load(new_content)
    if not isinstance(new, dict):
        return new_content

    changed = False

    # Merge tools section: add new tools, preserve existing
    new_tools = new.get("tools")
    if isinstance(new_tools, dict) and isinstance(existing.get("tools", {}), dict):
        existing_tools = existing.setdefault("tools", {})
        for tool_name, tool_cfg in new_tools.items():
            if tool_name not in existing_tools:
                existing_tools[tool_name] = tool_cfg
                changed = True

    # Update enabled_tools list if present in new config
    new_exec = new.get("execution")
    if isinstance(new_exec, dict) and isinstance(existing.get("execution", {}), dict):
        existing_exec = existing.setdefault("execution", {})
        new_enabled = new_exec.get("enabled_tools", [])
        existing_enabled_raw = existing_exec.get("enabled_tools")
        if isinstance(new_enabled, list) and isinstance(
            existing_enabled_raw,
            (list, type(None)),
        ):
            existing_enabled = set(existing_enabled_raw or [])
            merged_enabled = sorted(existing_enabled | set(new_enabled))
            if merged_enabled != sorted(existing_enabled):
                existing_exec["enabled_tools"] = merged_enabled
                changed = True
        elif isinstance(new_enabled, list) and new_enabled:
            existing_exec["enabled_tools"] = new_enabled
            changed = True

    if not changed:
        console.print(f"  [dim]{path} is already up to date.[/dim]")
        return None

    console.print(f"  [green]Merged new entries into {path}[/green]")
    return yaml.dump(existing, default_flow_style=False, sort_keys=False)


def _generate_native_configs(console: Console, *, force: bool) -> list[str]:
    """Generate optional native tool configuration files."""
    created: list[str] = []
    template = {
        "config": {
            "MD013": {
                "line_length": 88,
                "code_blocks": False,
                "tables": False,
            },
        },
    }
    path = Path(".markdownlint-cli2.jsonc")
    if _write_file(
        path,
        json.dumps(template, indent=2) + "\n",
        console,
        force=force,
    ):
        created.append(str(path))
    return created


@click.command("init")
@click.option(
    "--minimal",
    "-m",
    is_flag=True,
    help="Create a minimal config with fewer defaults.",
)
@click.option(
    "--force",
    "-f",
    is_flag=True,
    help="Overwrite existing configuration files.",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default=".lintro-config.yaml",
    help="Output file path (default: .lintro-config.yaml).",
)
@click.option(
    "--with-native-configs",
    is_flag=True,
    help="Also generate native tool configs (.markdownlint-cli2.jsonc).",
)
@click.option(
    "--profile",
    type=str,
    default=None,
    help="Install profile to resolve tools (default: recommended).",
)
@click.option(
    "--static",
    is_flag=True,
    help="Use built-in static templates instead of language detection.",
)
def init_command(
    minimal: bool,
    force: bool,
    output: str,
    with_native_configs: bool,
    profile: str | None,
    static: bool,
) -> None:
    """Initialize Lintro configuration for your project.

    Detects languages, enables appropriate tools in config, and prints
    next steps for installing tools and running checks.

    Args:
        minimal: Use minimal template with fewer defaults.
        force: Overwrite existing config file if it exists.
        output: Output file path for the config file.
        with_native_configs: Also generate native tool config files.
        profile: Profile used to select tools for enabled_tools.
        static: Use static templates instead of detection.

    Raises:
        SystemExit: If file exists and --force not provided, or write fails.
        click.UsageError: If the selected profile does not exist.
    """
    console = Console()
    output_path = Path(output)

    if static:
        config_content = MINIMAL_CONFIG_TEMPLATE if minimal else DEFAULT_CONFIG_TEMPLATE
        tool_names: list[str] = _extract_tool_names(config_content)
        detected_langs: list[str] = []
    else:
        registry = ManifestRegistry.load()
        detected_langs = detect_project_languages()
        effective_profile = profile or ("minimal" if minimal else "recommended")

        if effective_profile not in registry.profile_names:
            raise click.UsageError(
                f"Unknown profile {effective_profile!r}. "
                f"Available: {', '.join(registry.profile_names)}",
            )

        tool_list = registry.tools_for_profile(
            effective_profile,
            detected_langs if detected_langs else None,
        )
        tool_names = [t.name for t in tool_list]
        config_content = _generate_config(
            tool_names,
            detected_langs,
            minimal=minimal,
        )

    if output_path.exists() and not force:
        merged = _merge_config(output_path, config_content, console)
        if merged is None:
            return
        config_content = merged

    try:
        output_path.write_text(config_content, encoding="utf-8")
    except OSError as exc:
        console.print(f"[red]Error: Failed to write {output_path}: {exc}[/red]")
        raise SystemExit(1) from exc

    created_files = [str(output_path)]
    if with_native_configs:
        created_files.extend(_generate_native_configs(console, force=force))

    console.print()
    if len(created_files) == 1:
        console.print(
            Panel.fit(
                f"[bold green]Created {output_path}[/bold green] "
                f"with {len(tool_names)} tools",
                border_style="green",
            ),
        )
    else:
        files_list = "\n".join(f"  • {f}" for f in created_files)
        console.print(
            Panel.fit(
                f"[bold green]Created {len(created_files)} files:[/bold green]\n"
                f"{files_list}",
                border_style="green",
            ),
        )

    if not static:
        effective_profile = profile or ("minimal" if minimal else "recommended")
        if detected_langs:
            console.print(
                f"  [dim]Detected: {', '.join(detected_langs)} | "
                f"Profile: {effective_profile}[/dim]",
            )
        console.print()
        console.print("  [bold]Recommended:[/bold]")
        console.print(
            f"    lintro install --profile {effective_profile}   "
            "[dim]Install tools for this project[/dim]",
        )
    else:
        console.print()
        console.print("[bold cyan]Next steps:[/bold cyan]")
        console.print("  [dim]1.[/dim] Review and customize the configuration")
        console.print("  [dim]2.[/dim] Run [cyan]lintro config[/cyan] to view config")
        console.print("  [dim]3.[/dim] Run [cyan]lintro check .[/cyan] to lint")
    if not static:
        print_install_next_steps(console)
