"""Interactive setup command for project onboarding.

Detects project languages, recommends tools, installs missing ones, and
generates a project-appropriate .lintro-config.yaml. Inspired by Trunk's
zero-friction init and rustup's profile system.

Usage:
    lintro setup                      # Interactive onboarding
    lintro setup --profile ci --yes   # Non-interactive for CI
    lintro setup --dry-run            # Show plan without executing
"""

from __future__ import annotations

import sys
from pathlib import Path

import click
from rich.console import Console

from lintro.tools.core.install_context import RuntimeContext
from lintro.tools.core.tool_installer import ToolInstaller
from lintro.tools.core.tool_registry import ToolRegistry
from lintro.utils.project_detection import (
    detect_package_managers,
    detect_project_languages,
)


def _generate_config(
    tools: list[str],
    detected_langs: list[str],
) -> str:
    """Generate .lintro-config.yaml content for the given tools.

    Args:
        tools: List of tool names to enable.
        detected_langs: Detected languages for enforce settings.

    Returns:
        YAML config string.
    """
    lines = [
        "# Lintro configuration — generated by 'lintro setup'",
        "# Docs: https://github.com/lgtm-hq/py-lintro/tree/main/docs",
        "",
        "enforce:",
    ]

    # Python-specific enforce settings
    if "python" in detected_langs:
        lines.append("  line_length: 88")

    lines.extend(
        [
            "",
            "execution:",
            f"  enabled_tools: [{', '.join(sorted(tools))}]",
            "  tool_order: priority",
            "  fail_fast: false",
            "  parallel: true",
            "",
        ],
    )

    if "mypy" in tools:
        lines.extend(
            [
                "defaults:",
                "  mypy:",
                "    strict: true",
                "    ignore_missing_imports: true",
                "",
            ],
        )

    lines.append("tools:")
    for tool_name in sorted(tools):
        lines.append(f"  {tool_name}:")
        lines.append("    enabled: true")

    lines.append("")
    return "\n".join(lines)


@click.command(help=("""Set up lintro for your project.

Scans your project, detects languages and frameworks, recommends tools,
installs missing ones, and generates a .lintro-config.yaml.
"""))
@click.option(
    "--profile",
    type=str,
    help="Named profile (e.g., minimal, recommended, complete, ci).",
)
@click.option(
    "--yes",
    "-y",
    is_flag=True,
    help="Non-interactive mode (accept defaults).",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would happen without making changes.",
)
@click.option(
    "--skip-install",
    is_flag=True,
    help="Generate config only, don't install tools.",
)
@click.option(
    "--config",
    "config_path",
    type=str,
    default=".lintro-config.yaml",
    help="Config output path (default: .lintro-config.yaml).",
)
def setup_command(
    profile: str | None,
    *,
    yes: bool,
    dry_run: bool,
    skip_install: bool,
    config_path: str,
) -> None:
    """Set up lintro for your project.

    Scans your project, detects languages and frameworks, recommends tools,
    installs missing ones, and generates a .lintro-config.yaml.

    Args:
        profile: Named profile to use.
        yes: Non-interactive mode.
        dry_run: Show plan without executing.
        skip_install: Skip tool installation.
        config_path: Output path for config file.

    Raises:
        click.ClickException: When an invalid profile name is provided.

    Examples:
        lintro setup
        lintro setup --profile minimal --yes
        lintro setup --dry-run
        lintro setup --skip-install
    """
    console = Console()

    console.print()
    console.print("  [bold]Lintro Setup[/bold]")
    console.print("  [dim]Scanning project...[/dim]")
    console.print()

    # ── Detection ──
    detected_langs = detect_project_languages()
    pkg_managers = detect_package_managers()

    console.print("  [bold]Detected:[/bold]")
    if detected_langs:
        console.print(
            f"    Languages:   {', '.join(lang.title() for lang in detected_langs)}",
        )
    else:
        console.print("    Languages:   [dim]none detected[/dim]")
    if pkg_managers:
        mgr_display = ", ".join(
            f"{name} ({manifest})" for name, manifest in pkg_managers.items()
        )
        console.print(f"    Pkg Mgrs:    {mgr_display}")
    console.print()

    # ── Load registry ──
    registry = ToolRegistry.load()
    context = RuntimeContext.detect()

    # ── Resolve profile ──
    if not profile:
        # Show recommended tools (use the same resolver the install path uses)
        recommended = registry.tools_for_profile("recommended", detected_langs)
        if recommended:
            console.print(
                f"  [bold]Recommended tools for this project "
                f"({len(recommended)} tools):[/bold]",
            )
            console.print()

            # Group by language for display
            lang_tools: dict[str, list[str]] = {}
            for tool in recommended:
                for lang in tool.languages:
                    lang_tools.setdefault(lang, []).append(tool.name)

            for lang in sorted(lang_tools):
                tool_display = ", ".join(sorted(set(lang_tools[lang])))
                console.print(f"    {lang.title():<20}{tool_display}")

            console.print()

        if yes:
            profile = "recommended"
        else:
            # Interactive profile selection
            profiles = registry.profiles
            console.print("  [bold]Select profile:[/bold]")
            # Preferred display order, then any additional profiles
            preferred_order = ["recommended", "minimal", "complete", "ci"]
            profile_list = [p for p in preferred_order if p in profiles]
            profile_list.extend(p for p in sorted(profiles) if p not in preferred_order)
            default_idx = (
                profile_list.index("recommended") + 1
                if "recommended" in profile_list
                else 1
            )
            for i, pname in enumerate(profile_list, 1):
                desc = profiles[pname].description
                default = " (default)" if i == default_idx else ""
                console.print(f"    [{i}] {pname:<16}{desc}{default}")

            console.print()
            choice = click.prompt(
                "  Choice",
                type=click.IntRange(1, len(profile_list)),
                default=default_idx,
                show_default=False,
            )
            profile = profile_list[choice - 1]

    # Resolve profile to tool list
    if profile not in registry.profile_names:
        raise click.ClickException(
            f"Unknown profile {profile!r}. "
            f"Available: {', '.join(registry.profile_names)}",
        )
    selected_tools = registry.tools_for_profile(profile, detected_langs)
    tool_names: list[str] = [t.name for t in selected_tools]

    console.print()
    console.print(
        f"  [dim]Profile: {profile} ({len(selected_tools)} tools)[/dim]",
    )

    # ── Install check ──
    if not skip_install:
        installer = ToolInstaller(registry, context)
        plan = installer.plan(
            tools=tool_names,
            detected_langs=detected_langs,
        )

        if plan.has_work:
            console.print()
            console.print(
                f"  [bold]Missing tools ({len(plan.to_install)}):[/bold]",
            )
            for tool, cmd in plan.to_install:
                console.print(
                    f"    {tool.name:<20}({tool.install_type}) [dim]{cmd}[/dim]",
                )

            if dry_run:
                console.print()
                console.print(
                    f"  [dim]Dry run: would install "
                    f"{len(plan.to_install)} tool(s).[/dim]",
                )
            elif yes or click.confirm(
                "\n  Install missing tools?",
                default=True,
            ):
                console.print()
                results = installer.execute(plan)
                succeeded = sum(1 for r in results if r.success)
                failed = sum(1 for r in results if not r.success)
                for r in results:
                    if r.success:
                        console.print(f"  [green]OK[/green]  {r.tool.name}")
                    else:
                        console.print(
                            f"  [red]FAIL[/red]  {r.tool.name}: {r.message}",
                        )
                if failed > 0:
                    console.print(
                        f"\n  [yellow]{succeeded} installed, "
                        f"{failed} failed[/yellow]",
                    )
                    # Report outdated/skipped before exiting
                    if plan.outdated:
                        console.print()
                        console.print(
                            f"  [yellow]Outdated tools"
                            f" ({len(plan.outdated)}):[/yellow]",
                        )
                        for tool, current_ver in plan.outdated:
                            console.print(
                                f"    {tool.name:<20}"
                                f"[yellow]{current_ver}[/yellow]"
                                f" → [green]{tool.version}[/green]",
                            )
                    if plan.skipped:
                        console.print()
                        console.print(
                            f"  [yellow]Skipped tools"
                            f" ({len(plan.skipped)}):[/yellow]",
                        )
                        for tool, reason in plan.skipped:
                            console.print(
                                f"    {tool.name:<20}[dim]{reason}[/dim]",
                            )
                    sys.exit(1)
            else:
                console.print(
                    "\n  [yellow]Setup incomplete: tool installation "
                    "declined.[/yellow]",
                )
                if plan.outdated:
                    console.print(
                        f"  [yellow]Outdated: {len(plan.outdated)} tool(s)"
                        f" (use --upgrade to update)[/yellow]",
                    )
                if plan.skipped:
                    console.print(
                        f"  [yellow]Skipped: {len(plan.skipped)} tool(s)"
                        f" require manual installation[/yellow]",
                    )
                sys.exit(1)

        # Always surface skipped/outdated regardless of install outcome
        if plan.outdated:
            console.print()
            console.print(
                f"  [yellow]Outdated tools ({len(plan.outdated)}):[/yellow]",
            )
            for tool, current_ver in plan.outdated:
                console.print(
                    f"    {tool.name:<20}[yellow]{current_ver}[/yellow]"
                    f" → [green]{tool.version}[/green]",
                )
        if plan.skipped:
            console.print()
            console.print(
                f"  [yellow]Skipped tools ({len(plan.skipped)}):[/yellow]",
            )
            for tool, reason in plan.skipped:
                console.print(f"    {tool.name:<20}[dim]{reason}[/dim]")
        if plan.outdated:
            console.print()
            console.print(
                "  [yellow]Run 'lintro install --upgrade' to update.[/yellow]",
            )
        if plan.skipped:
            console.print()
            console.print(
                "  [yellow]Some tools require manual installation "
                "(see details above).[/yellow]",
            )
        if (plan.outdated or plan.skipped) and not dry_run:
            sys.exit(1)
        elif not plan.has_work and not dry_run:
            console.print(
                f"  [green]All {profile} tools already installed.[/green]",
            )

    # ── Generate config ──
    config_file = Path(config_path)
    if (
        config_file.exists()
        and not yes
        and not dry_run
        and not click.confirm(
            f"\n  {config_path} already exists. Overwrite?",
            default=False,
        )
    ):
        console.print("  [dim]Skipping config generation.[/dim]")
        _print_next_steps(console)
        return

    config_content = _generate_config(tool_names, detected_langs)

    if dry_run:
        console.print()
        console.print(f"  [dim]Dry run: would write {config_path}[/dim]")
    else:
        try:
            config_file.parent.mkdir(parents=True, exist_ok=True)
            config_file.write_text(config_content, encoding="utf-8")
        except OSError as exc:
            raise click.ClickException(
                f"Failed to write {config_path}: {exc}",
            ) from exc
        console.print()
        console.print(
            f"  [green]Generated {config_path} "
            f"with {len(tool_names)} tools enabled.[/green]",
        )

    _print_next_steps(console)


def _print_next_steps(console: Console) -> None:
    """Print post-setup guidance."""
    console.print()
    console.print("  [bold]Next steps:[/bold]")
    console.print("    lintro check .     [dim]Check all files[/dim]")
    console.print("    lintro fmt .       [dim]Auto-fix formatting[/dim]")
    console.print("    lintro doctor      [dim]Verify tool health[/dim]")
    console.print()
