"""Shared constants for AI diff review."""

from __future__ import annotations

CUSTOM_CHECKLIST_ID_START = 10_000
TIER1_CHECKLIST_COUNT = 15
TIER1_CHECKLIST_ID_START = 1
TIER1_CHECKLIST_ID_END = 15
TIER2_CHECKLIST_ID_START = 100
TIER2_CHECKLIST_MIN_COUNT = 40
TIER1_FAIL_OPEN_SECURITY_ITEM_ID = 9

__all__ = [
    "CUSTOM_CHECKLIST_ID_START",
    "TIER1_CHECKLIST_COUNT",
    "TIER1_CHECKLIST_ID_END",
    "TIER1_CHECKLIST_ID_START",
    "TIER1_FAIL_OPEN_SECURITY_ITEM_ID",
    "TIER2_CHECKLIST_ID_START",
    "TIER2_CHECKLIST_MIN_COUNT",
]
