"""Unit tests for the SARIF ingestion parser (proof of concept, issue #1066).

These tests validate the SARIF 2.1.0 -> lintro ``BaseIssue`` mapping against
real SARIF logs generated by ruff and semgrep, plus synthetic fixtures that
exercise edge cases (severity levels, missing locations, multi-run logs, and
malformed input). They do not exercise any tool plugin; SARIF is not wired
into lintro's execution path.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from assertpy import assert_that

from lintro.enums.severity_level import SeverityLevel
from lintro.parsers.sarif.sarif_issue import SarifIssue
from lintro.parsers.sarif.sarif_parser import parse_sarif_output

_FIXTURES = Path(__file__).parent / "sarif_fixtures"


@pytest.fixture
def ruff_sarif() -> str:
    """Return the real ruff SARIF fixture as a string.

    Returns:
        The contents of the ruff SARIF fixture file.
    """
    return (_FIXTURES / "ruff.sarif").read_text()


@pytest.fixture
def semgrep_sarif() -> str:
    """Return the real semgrep SARIF fixture as a string.

    Returns:
        The contents of the semgrep SARIF fixture file.
    """
    return (_FIXTURES / "semgrep.sarif").read_text()


def _make_sarif(results: list[dict[str, Any]], *, driver: str = "acme") -> str:
    """Build a minimal single-run SARIF log around the given results.

    Args:
        results: The list of SARIF ``result`` objects to embed.
        driver: The driver name to record for the run.

    Returns:
        A JSON-encoded SARIF 2.1.0 log.
    """
    return json.dumps(
        {
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {"driver": {"name": driver, "rules": []}},
                    "results": results,
                },
            ],
        },
    )


def test_ruff_fixture_yields_expected_issue_count(ruff_sarif: str) -> None:
    """Real ruff SARIF produces one issue per result."""
    issues = parse_sarif_output(ruff_sarif)
    assert_that(issues).is_length(3)


def test_ruff_fixture_maps_core_fields(ruff_sarif: str) -> None:
    """The first ruff finding maps file, line, column, code, and message."""
    first = parse_sarif_output(ruff_sarif)[0]
    assert_that(first.file).is_equal_to("/project/sample.py")
    assert_that(first.line).is_equal_to(1)
    assert_that(first.column).is_equal_to(8)
    assert_that(first.code).is_equal_to("F401")
    assert_that(first.message).contains("imported but unused")
    assert_that(first.tool_name).is_equal_to("ruff")


def test_ruff_fixture_maps_severity_and_fixability(ruff_sarif: str) -> None:
    """Ruff's ``error`` level and ``fixes`` array map to severity/fixable."""
    first = parse_sarif_output(ruff_sarif)[0]
    assert_that(first.get_severity()).is_equal_to(SeverityLevel.ERROR)
    assert_that(first.fixable).is_true()


def test_ruff_fixture_resolves_rule_help_uri(ruff_sarif: str) -> None:
    """A result's ``ruleId`` resolves to the rule's ``helpUri`` for doc_url."""
    first = parse_sarif_output(ruff_sarif)[0]
    assert_that(first.doc_url).starts_with("https://docs.astral.sh/ruff/")


def test_semgrep_fixture_maps_relative_uri(semgrep_sarif: str) -> None:
    """Semgrep uses relative artifact URIs, which map through unchanged."""
    issues = parse_sarif_output(semgrep_sarif)
    assert_that(issues).is_length(1)
    issue = issues[0]
    assert_that(issue.file).is_equal_to("sample.py")
    assert_that(issue.line).is_equal_to(7)
    assert_that(issue.code).is_equal_to("dangerous-eval")
    assert_that(issue.get_severity()).is_equal_to(SeverityLevel.ERROR)
    assert_that(issue.fixable).is_false()


@pytest.mark.parametrize(
    ("level", "expected"),
    [
        ("error", SeverityLevel.ERROR),
        ("warning", SeverityLevel.WARNING),
        ("note", SeverityLevel.INFO),
        ("none", SeverityLevel.INFO),
        ("ERROR", SeverityLevel.ERROR),
    ],
)
def test_severity_level_mapping(level: str, expected: SeverityLevel) -> None:
    """Each SARIF level maps onto the expected lintro severity."""
    result = {
        "ruleId": "X1",
        "level": level,
        "message": {"text": "m"},
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {"uri": "a.py"},
                    "region": {"startLine": 1, "startColumn": 1},
                },
            },
        ],
    }
    issue = parse_sarif_output(_make_sarif([result]))[0]
    assert_that(issue.get_severity()).is_equal_to(expected)


def test_missing_level_falls_back_to_rule_default_config() -> None:
    """A result without a level inherits the rule's defaultConfiguration."""
    log = json.dumps(
        {
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {
                        "driver": {
                            "name": "acme",
                            "rules": [
                                {
                                    "id": "X1",
                                    "defaultConfiguration": {"level": "error"},
                                    "helpUri": "https://example.test/X1",
                                },
                            ],
                        },
                    },
                    "results": [
                        {
                            "ruleId": "X1",
                            "message": {"text": "m"},
                            "locations": [
                                {
                                    "physicalLocation": {
                                        "artifactLocation": {"uri": "a.py"},
                                        "region": {"startLine": 3},
                                    },
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    )
    issue = parse_sarif_output(log)[0]
    assert_that(issue.get_severity()).is_equal_to(SeverityLevel.ERROR)
    assert_that(issue.doc_url).is_equal_to("https://example.test/X1")


def test_missing_level_defaults_to_warning() -> None:
    """With neither a result level nor a rule default, severity is WARNING."""
    result = {
        "ruleId": "X1",
        "message": {"text": "m"},
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {"uri": "a.py"},
                    "region": {"startLine": 1},
                },
            },
        ],
    }
    issue = parse_sarif_output(_make_sarif([result]))[0]
    assert_that(issue.get_severity()).is_equal_to(SeverityLevel.WARNING)


def test_rule_index_resolution() -> None:
    """A result referencing a rule by ``ruleIndex`` resolves its helpUri."""
    log = json.dumps(
        {
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {
                        "driver": {
                            "name": "acme",
                            "rules": [
                                {"id": "A", "helpUri": "https://example.test/A"},
                                {"id": "B", "helpUri": "https://example.test/B"},
                            ],
                        },
                    },
                    "results": [
                        {
                            "ruleIndex": 1,
                            "level": "warning",
                            "message": {"text": "m"},
                            "locations": [
                                {
                                    "physicalLocation": {
                                        "artifactLocation": {"uri": "a.py"},
                                        "region": {"startLine": 1},
                                    },
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    )
    issue = parse_sarif_output(log)[0]
    assert_that(issue.code).is_equal_to("B")
    assert_that(issue.doc_url).is_equal_to("https://example.test/B")


def test_file_uri_is_decoded_to_path() -> None:
    """A ``file://`` URI with percent-encoding decodes to a plain path."""
    result = {
        "ruleId": "X1",
        "level": "warning",
        "message": {"text": "m"},
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {"uri": "file:///tmp/my%20dir/a.py"},
                    "region": {"startLine": 1},
                },
            },
        ],
    }
    issue = parse_sarif_output(_make_sarif([result]))[0]
    assert_that(issue.file).is_equal_to("/tmp/my dir/a.py")


def test_result_without_location_is_skipped() -> None:
    """SARIF permits location-free results, which lintro cannot place."""
    result = {"ruleId": "X1", "level": "error", "message": {"text": "m"}}
    issues = parse_sarif_output(_make_sarif([result]))
    assert_that(issues).is_empty()


def test_multi_run_log_flattens_and_attributes_tool() -> None:
    """Multiple runs flatten into one list, each tagged with its driver."""
    log = json.dumps(
        {
            "version": "2.1.0",
            "runs": [
                {
                    "tool": {"driver": {"name": "tool-a", "rules": []}},
                    "results": [
                        {
                            "ruleId": "A1",
                            "level": "error",
                            "message": {"text": "a"},
                            "locations": [
                                {
                                    "physicalLocation": {
                                        "artifactLocation": {"uri": "a.py"},
                                        "region": {"startLine": 1},
                                    },
                                },
                            ],
                        },
                    ],
                },
                {
                    "tool": {"driver": {"name": "tool-b", "rules": []}},
                    "results": [
                        {
                            "ruleId": "B1",
                            "level": "warning",
                            "message": {"text": "b"},
                            "locations": [
                                {
                                    "physicalLocation": {
                                        "artifactLocation": {"uri": "b.py"},
                                        "region": {"startLine": 2},
                                    },
                                },
                            ],
                        },
                    ],
                },
            ],
        },
    )
    issues = parse_sarif_output(log)
    assert_that(issues).is_length(2)
    assert_that({i.tool_name for i in issues}).is_equal_to({"tool-a", "tool-b"})


def test_end_region_is_captured() -> None:
    """End line/column of a region are captured when present."""
    result = {
        "ruleId": "X1",
        "level": "warning",
        "message": {"text": "m"},
        "locations": [
            {
                "physicalLocation": {
                    "artifactLocation": {"uri": "a.py"},
                    "region": {
                        "startLine": 1,
                        "startColumn": 2,
                        "endLine": 3,
                        "endColumn": 4,
                    },
                },
            },
        ],
    }
    issue = parse_sarif_output(_make_sarif([result]))[0]
    assert_that(issue.end_line).is_equal_to(3)
    assert_that(issue.end_column).is_equal_to(4)


def test_display_row_uses_shared_base_mapping() -> None:
    """SarifIssue integrates with BaseIssue's unified display row."""
    issue = SarifIssue(
        file="a.py",
        line=5,
        column=2,
        message="boom",
        code="X1",
        level=str(SeverityLevel.ERROR),
        fixable=True,
    )
    row = issue.to_display_row()
    assert_that(row["file"]).is_equal_to("a.py")
    assert_that(row["code"]).is_equal_to("X1")
    assert_that(row["severity"]).is_equal_to(str(SeverityLevel.ERROR))
    assert_that(row["fixable"]).is_equal_to("Yes")


@pytest.mark.parametrize(
    "bad_input",
    ["", "   ", None, "not json", "[1, 2, 3]", '{"no": "runs"}'],
)
def test_malformed_input_returns_empty(bad_input: str | None) -> None:
    """Blank, invalid, or structurally unexpected input yields no issues."""
    assert_that(parse_sarif_output(bad_input)).is_empty()
