"""Auto-generated SPDX license identifiers. Do not edit by hand.

Run ``python3 scripts/release/generate_spdx_data.py`` to regenerate.
"""

# Source: https://spdx.org/licenses/licenses.json
# licenseListVersion: "3.28.0"
# releaseDate: "2026-02-20T00:00:00Z"

from __future__ import annotations

SPDX_LIST_VERSION: str = "3.28.0"
SPDX_LIST_RELEASE_DATE: str = "2026-02-20T00:00:00Z"

SPDX_LICENSE_IDS: frozenset[str] = frozenset(
    {
        "0BSD",
        "3D-Slicer-1.0",
        "AAL",
        "ADSL",
        "AFL-1.1",
        "AFL-1.2",
        "AFL-2.0",
        "AFL-2.1",
        "AFL-3.0",
        "AGPL-1.0",
        "AGPL-1.0-only",
        "AGPL-1.0-or-later",
        "AGPL-3.0",
        "AGPL-3.0-only",
        "AGPL-3.0-or-later",
        "ALGLIB-Documentation",
        "AMD-newlib",
        "AMDPLPA",
        "AML",
        "AML-glslang",
        "AMPAS",
        "ANTLR-PD",
        "ANTLR-PD-fallback",
        "APAFML",
        "APL-1.0",
        "APSL-1.0",
        "APSL-1.1",
        "APSL-1.2",
        "APSL-2.0",
        "ASWF-Digital-Assets-1.0",
        "ASWF-Digital-Assets-1.1",
        "Abstyles",
        "AdaCore-doc",
        "Adobe-2006",
        "Adobe-Display-PostScript",
        "Adobe-Glyph",
        "Adobe-Utopia",
        "Advanced-Cryptics-Dictionary",
        "Afmparse",
        "Aladdin",
        "Apache-1.0",
        "Apache-1.1",
        "Apache-2.0",
        "App-s2p",
        "Arphic-1999",
        "Artistic-1.0",
        "Artistic-1.0-Perl",
        "Artistic-1.0-cl8",
        "Artistic-2.0",
        "Artistic-dist",
        "Aspell-RU",
        "BOLA-1.1",
        "BSD-1-Clause",
        "BSD-2-Clause",
        "BSD-2-Clause-Darwin",
        "BSD-2-Clause-FreeBSD",
        "BSD-2-Clause-NetBSD",
        "BSD-2-Clause-Patent",
        "BSD-2-Clause-Views",
        "BSD-2-Clause-first-lines",
        "BSD-2-Clause-pkgconf-disclaimer",
        "BSD-3-Clause",
        "BSD-3-Clause-Attribution",
        "BSD-3-Clause-Clear",
        "BSD-3-Clause-HP",
        "BSD-3-Clause-LBNL",
        "BSD-3-Clause-Modification",
        "BSD-3-Clause-No-Military-License",
        "BSD-3-Clause-No-Nuclear-License",
        "BSD-3-Clause-No-Nuclear-License-2014",
        "BSD-3-Clause-No-Nuclear-Warranty",
        "BSD-3-Clause-Open-MPI",
        "BSD-3-Clause-Sun",
        "BSD-3-Clause-Tso",
        "BSD-3-Clause-acpica",
        "BSD-3-Clause-flex",
        "BSD-4-Clause",
        "BSD-4-Clause-Shortened",
        "BSD-4-Clause-UC",
        "BSD-4.3RENO",
        "BSD-4.3TAHOE",
        "BSD-Advertising-Acknowledgement",
        "BSD-Attribution-HPND-disclaimer",
        "BSD-Inferno-Nettverk",
        "BSD-Mark-Modifications",
        "BSD-Protection",
        "BSD-Source-Code",
        "BSD-Source-beginning-file",
        "BSD-Systemics",
        "BSD-Systemics-W3Works",
        "BSL-1.0",
        "BUSL-1.1",
        "Baekmuk",
        "Bahyph",
        "Barr",
        "Beerware",
        "BitTorrent-1.0",
        "BitTorrent-1.1",
        "Bitstream-Charter",
        "Bitstream-Vera",
        "BlueOak-1.0.0",
        "Boehm-GC",
        "Boehm-GC-without-fee",
        "Borceux",
        "Brian-Gladman-2-Clause",
        "Brian-Gladman-3-Clause",
        "Buddy",
        "C-UDA-1.0",
        "CAL-1.0",
        "CAL-1.0-Combined-Work-Exception",
        "CAPEC-tou",
        "CATOSL-1.1",
        "CC-BY-1.0",
        "CC-BY-2.0",
        "CC-BY-2.5",
        "CC-BY-2.5-AU",
        "CC-BY-3.0",
        "CC-BY-3.0-AT",
        "CC-BY-3.0-AU",
        "CC-BY-3.0-DE",
        "CC-BY-3.0-IGO",
        "CC-BY-3.0-NL",
        "CC-BY-3.0-US",
        "CC-BY-4.0",
        "CC-BY-NC-1.0",
        "CC-BY-NC-2.0",
        "CC-BY-NC-2.5",
        "CC-BY-NC-3.0",
        "CC-BY-NC-3.0-DE",
        "CC-BY-NC-4.0",
        "CC-BY-NC-ND-1.0",
        "CC-BY-NC-ND-2.0",
        "CC-BY-NC-ND-2.5",
        "CC-BY-NC-ND-3.0",
        "CC-BY-NC-ND-3.0-DE",
        "CC-BY-NC-ND-3.0-IGO",
        "CC-BY-NC-ND-4.0",
        "CC-BY-NC-SA-1.0",
        "CC-BY-NC-SA-2.0",
        "CC-BY-NC-SA-2.0-DE",
        "CC-BY-NC-SA-2.0-FR",
        "CC-BY-NC-SA-2.0-UK",
        "CC-BY-NC-SA-2.5",
        "CC-BY-NC-SA-3.0",
        "CC-BY-NC-SA-3.0-DE",
        "CC-BY-NC-SA-3.0-IGO",
        "CC-BY-NC-SA-4.0",
        "CC-BY-ND-1.0",
        "CC-BY-ND-2.0",
        "CC-BY-ND-2.5",
        "CC-BY-ND-3.0",
        "CC-BY-ND-3.0-DE",
        "CC-BY-ND-4.0",
        "CC-BY-SA-1.0",
        "CC-BY-SA-2.0",
        "CC-BY-SA-2.0-UK",
        "CC-BY-SA-2.1-JP",
        "CC-BY-SA-2.5",
        "CC-BY-SA-3.0",
        "CC-BY-SA-3.0-AT",
        "CC-BY-SA-3.0-DE",
        "CC-BY-SA-3.0-IGO",
        "CC-BY-SA-4.0",
        "CC-PDDC",
        "CC-PDM-1.0",
        "CC-SA-1.0",
        "CC0-1.0",
        "CDDL-1.0",
        "CDDL-1.1",
        "CDL-1.0",
        "CDLA-Permissive-1.0",
        "CDLA-Permissive-2.0",
        "CDLA-Sharing-1.0",
        "CECILL-1.0",
        "CECILL-1.1",
        "CECILL-2.0",
        "CECILL-2.1",
        "CECILL-B",
        "CECILL-C",
        "CERN-OHL-1.1",
        "CERN-OHL-1.2",
        "CERN-OHL-P-2.0",
        "CERN-OHL-S-2.0",
        "CERN-OHL-W-2.0",
        "CFITSIO",
        "CMU-Mach",
        "CMU-Mach-nodoc",
        "CNRI-Jython",
        "CNRI-Python",
        "CNRI-Python-GPL-Compatible",
        "COIL-1.0",
        "CPAL-1.0",
        "CPL-1.0",
        "CPOL-1.02",
        "CUA-OPL-1.0",
        "Caldera",
        "Caldera-no-preamble",
        "Catharon",
        "ClArtistic",
        "Clips",
        "Community-Spec-1.0",
        "Condor-1.1",
        "Cornell-Lossless-JPEG",
        "Cronyx",
        "Crossword",
        "CryptoSwift",
        "CrystalStacker",
        "Cube",
        "D-FSL-1.0",
        "DEC-3-Clause",
        "DL-DE-BY-2.0",
        "DL-DE-ZERO-2.0",
        "DOC",
        "DRL-1.0",
        "DRL-1.1",
        "DSDP",
        "DocBook-DTD",
        "DocBook-Schema",
        "DocBook-Stylesheet",
        "DocBook-XML",
        "Dotseqn",
        "ECL-1.0",
        "ECL-2.0",
        "EFL-1.0",
        "EFL-2.0",
        "EPICS",
        "EPL-1.0",
        "EPL-2.0",
        "ESA-PL-permissive-2.4",
        "ESA-PL-strong-copyleft-2.4",
        "ESA-PL-weak-copyleft-2.4",
        "EUDatagrid",
        "EUPL-1.0",
        "EUPL-1.1",
        "EUPL-1.2",
        "Elastic-2.0",
        "Entessa",
        "ErlPL-1.1",
        "Eurosym",
        "FBM",
        "FDK-AAC",
        "FSFAP",
        "FSFAP-no-warranty-disclaimer",
        "FSFUL",
        "FSFULLR",
        "FSFULLRSD",
        "FSFULLRWD",
        "FSL-1.1-ALv2",
        "FSL-1.1-MIT",
        "FTL",
        "Fair",
        "Ferguson-Twofish",
        "Frameworx-1.0",
        "FreeBSD-DOC",
        "FreeImage",
        "Furuseth",
        "GCR-docs",
        "GD",
        "GFDL-1.1",
        "GFDL-1.1-invariants-only",
        "GFDL-1.1-invariants-or-later",
        "GFDL-1.1-no-invariants-only",
        "GFDL-1.1-no-invariants-or-later",
        "GFDL-1.1-only",
        "GFDL-1.1-or-later",
        "GFDL-1.2",
        "GFDL-1.2-invariants-only",
        "GFDL-1.2-invariants-or-later",
        "GFDL-1.2-no-invariants-only",
        "GFDL-1.2-no-invariants-or-later",
        "GFDL-1.2-only",
        "GFDL-1.2-or-later",
        "GFDL-1.3",
        "GFDL-1.3-invariants-only",
        "GFDL-1.3-invariants-or-later",
        "GFDL-1.3-no-invariants-only",
        "GFDL-1.3-no-invariants-or-later",
        "GFDL-1.3-only",
        "GFDL-1.3-or-later",
        "GL2PS",
        "GLWTPL",
        "GPL-1.0",
        "GPL-1.0+",
        "GPL-1.0-only",
        "GPL-1.0-or-later",
        "GPL-2.0",
        "GPL-2.0+",
        "GPL-2.0-only",
        "GPL-2.0-or-later",
        "GPL-2.0-with-GCC-exception",
        "GPL-2.0-with-autoconf-exception",
        "GPL-2.0-with-bison-exception",
        "GPL-2.0-with-classpath-exception",
        "GPL-2.0-with-font-exception",
        "GPL-3.0",
        "GPL-3.0+",
        "GPL-3.0-only",
        "GPL-3.0-or-later",
        "GPL-3.0-with-GCC-exception",
        "GPL-3.0-with-autoconf-exception",
        "Game-Programming-Gems",
        "Giftware",
        "Glide",
        "Glulxe",
        "Graphics-Gems",
        "Gutmann",
        "HDF5",
        "HIDAPI",
        "HP-1986",
        "HP-1989",
        "HPND",
        "HPND-DEC",
        "HPND-Fenneberg-Livingston",
        "HPND-INRIA-IMAG",
        "HPND-Intel",
        "HPND-Kevlin-Henney",
        "HPND-MIT-disclaimer",
        "HPND-Markus-Kuhn",
        "HPND-Netrek",
        "HPND-Pbmplus",
        "HPND-SMC",
        "HPND-UC",
        "HPND-UC-export-US",
        "HPND-doc",
        "HPND-doc-sell",
        "HPND-export-US",
        "HPND-export-US-acknowledgement",
        "HPND-export-US-modify",
        "HPND-export2-US",
        "HPND-merchantability-variant",
        "HPND-sell-MIT-disclaimer-xserver",
        "HPND-sell-regexpr",
        "HPND-sell-variant",
        "HPND-sell-variant-MIT-disclaimer",
        "HPND-sell-variant-MIT-disclaimer-rev",
        "HPND-sell-variant-critical-systems",
        "HTMLTIDY",
        "HaskellReport",
        "Hippocratic-2.1",
        "IBM-pibs",
        "ICU",
        "IEC-Code-Components-EULA",
        "IJG",
        "IJG-short",
        "IPA",
        "IPL-1.0",
        "ISC",
        "ISC-Veillard",
        "ISO-permission",
        "ImageMagick",
        "Imlib2",
        "Info-ZIP",
        "Inner-Net-2.0",
        "InnoSetup",
        "Intel",
        "Intel-ACPI",
        "Interbase-1.0",
        "JPL-image",
        "JPNIC",
        "JSON",
        "Jam",
        "JasPer-2.0",
        "Kastrup",
        "Kazlib",
        "Knuth-CTAN",
        "LAL-1.2",
        "LAL-1.3",
        "LGPL-2.0",
        "LGPL-2.0+",
        "LGPL-2.0-only",
        "LGPL-2.0-or-later",
        "LGPL-2.1",
        "LGPL-2.1+",
        "LGPL-2.1-only",
        "LGPL-2.1-or-later",
        "LGPL-3.0",
        "LGPL-3.0+",
        "LGPL-3.0-only",
        "LGPL-3.0-or-later",
        "LGPLLR",
        "LOOP",
        "LPD-document",
        "LPL-1.0",
        "LPL-1.02",
        "LPPL-1.0",
        "LPPL-1.1",
        "LPPL-1.2",
        "LPPL-1.3a",
        "LPPL-1.3c",
        "LZMA-SDK-9.11-to-9.20",
        "LZMA-SDK-9.22",
        "Latex2e",
        "Latex2e-translated-notice",
        "Leptonica",
        "LiLiQ-P-1.1",
        "LiLiQ-R-1.1",
        "LiLiQ-Rplus-1.1",
        "Libpng",
        "Linux-OpenIB",
        "Linux-man-pages-1-para",
        "Linux-man-pages-copyleft",
        "Linux-man-pages-copyleft-2-para",
        "Linux-man-pages-copyleft-var",
        "Lucida-Bitmap-Fonts",
        "MIPS",
        "MIT",
        "MIT-0",
        "MIT-CMU",
        "MIT-Click",
        "MIT-Festival",
        "MIT-Khronos-old",
        "MIT-Modern-Variant",
        "MIT-STK",
        "MIT-Wu",
        "MIT-advertising",
        "MIT-enna",
        "MIT-feh",
        "MIT-open-group",
        "MIT-testregex",
        "MITNFA",
        "MMIXware",
        "MMPL-1.0.1",
        "MPEG-SSG",
        "MPL-1.0",
        "MPL-1.1",
        "MPL-2.0",
        "MPL-2.0-no-copyleft-exception",
        "MS-LPL",
        "MS-PL",
        "MS-RL",
        "MTLL",
        "Mackerras-3-Clause",
        "Mackerras-3-Clause-acknowledgment",
        "MakeIndex",
        "Martin-Birgmeier",
        "McPhee-slideshow",
        "Minpack",
        "MirOS",
        "Motosoto",
        "MulanPSL-1.0",
        "MulanPSL-2.0",
        "Multics",
        "Mup",
        "NAIST-2003",
        "NASA-1.3",
        "NBPL-1.0",
        "NCBI-PD",
        "NCGL-UK-2.0",
        "NCL",
        "NCSA",
        "NGPL",
        "NICTA-1.0",
        "NIST-PD",
        "NIST-PD-TNT",
        "NIST-PD-fallback",
        "NIST-Software",
        "NLOD-1.0",
        "NLOD-2.0",
        "NLPL",
        "NOSL",
        "NPL-1.0",
        "NPL-1.1",
        "NPOSL-3.0",
        "NRL",
        "NTIA-PD",
        "NTP",
        "NTP-0",
        "Naumen",
        "Net-SNMP",
        "NetCDF",
        "Newsletr",
        "Nokia",
        "Noweb",
        "Nunit",
        "O-UDA-1.0",
        "OAR",
        "OCCT-PL",
        "OCLC-2.0",
        "ODC-By-1.0",
        "ODbL-1.0",
        "OFFIS",
        "OFL-1.0",
        "OFL-1.0-RFN",
        "OFL-1.0-no-RFN",
        "OFL-1.1",
        "OFL-1.1-RFN",
        "OFL-1.1-no-RFN",
        "OGC-1.0",
        "OGDL-Taiwan-1.0",
        "OGL-Canada-2.0",
        "OGL-UK-1.0",
        "OGL-UK-2.0",
        "OGL-UK-3.0",
        "OGTSL",
        "OLDAP-1.1",
        "OLDAP-1.2",
        "OLDAP-1.3",
        "OLDAP-1.4",
        "OLDAP-2.0",
        "OLDAP-2.0.1",
        "OLDAP-2.1",
        "OLDAP-2.2",
        "OLDAP-2.2.1",
        "OLDAP-2.2.2",
        "OLDAP-2.3",
        "OLDAP-2.4",
        "OLDAP-2.5",
        "OLDAP-2.6",
        "OLDAP-2.7",
        "OLDAP-2.8",
        "OLFL-1.3",
        "OML",
        "OPL-1.0",
        "OPL-UK-3.0",
        "OPUBL-1.0",
        "OSC-1.0",
        "OSET-PL-2.1",
        "OSL-1.0",
        "OSL-1.1",
        "OSL-2.0",
        "OSL-2.1",
        "OSL-3.0",
        "OSSP",
        "OpenMDW-1.0",
        "OpenPBS-2.3",
        "OpenSSL",
        "OpenSSL-standalone",
        "OpenVision",
        "PADL",
        "PDDL-1.0",
        "PHP-3.0",
        "PHP-3.01",
        "PPL",
        "PSF-2.0",
        "ParaType-Free-Font-1.3",
        "Parity-6.0.0",
        "Parity-7.0.0",
        "Pixar",
        "Plexus",
        "PolyForm-Noncommercial-1.0.0",
        "PolyForm-Small-Business-1.0.0",
        "PostgreSQL",
        "Python-2.0",
        "Python-2.0.1",
        "QPL-1.0",
        "QPL-1.0-INRIA-2004",
        "Qhull",
        "RHeCos-1.1",
        "RPL-1.1",
        "RPL-1.5",
        "RPSL-1.0",
        "RSA-MD",
        "RSCPL",
        "Rdisc",
        "Ruby",
        "Ruby-pty",
        "SAX-PD",
        "SAX-PD-2.0",
        "SCEA",
        "SGI-B-1.0",
        "SGI-B-1.1",
        "SGI-B-2.0",
        "SGI-OpenGL",
        "SGMLUG-PM",
        "SGP4",
        "SHL-0.5",
        "SHL-0.51",
        "SISSL",
        "SISSL-1.2",
        "SL",
        "SMAIL-GPL",
        "SMLNJ",
        "SMPPL",
        "SNIA",
        "SOFA",
        "SPL-1.0",
        "SSH-OpenSSH",
        "SSH-short",
        "SSLeay-standalone",
        "SSPL-1.0",
        "SUL-1.0",
        "SWL",
        "Saxpath",
        "SchemeReport",
        "Sendmail",
        "Sendmail-8.23",
        "Sendmail-Open-Source-1.1",
        "SimPL-2.0",
        "Sleepycat",
        "Soundex",
        "Spencer-86",
        "Spencer-94",
        "Spencer-99",
        "StandardML-NJ",
        "SugarCRM-1.1.3",
        "Sun-PPP",
        "Sun-PPP-2000",
        "SunPro",
        "Symlinks",
        "TAPR-OHL-1.0",
        "TCL",
        "TCP-wrappers",
        "TGPPL-1.0",
        "TMate",
        "TORQUE-1.1",
        "TOSL",
        "TPDL",
        "TPL-1.0",
        "TTWL",
        "TTYP0",
        "TU-Berlin-1.0",
        "TU-Berlin-2.0",
        "TekHVC",
        "TermReadKey",
        "ThirdEye",
        "TrustedQSL",
        "UCAR",
        "UCL-1.0",
        "UMich-Merit",
        "UPL-1.0",
        "URT-RLE",
        "Ubuntu-font-1.0",
        "UnRAR",
        "Unicode-3.0",
        "Unicode-DFS-2015",
        "Unicode-DFS-2016",
        "Unicode-TOU",
        "UnixCrypt",
        "Unlicense",
        "Unlicense-libtelnet",
        "Unlicense-libwhirlpool",
        "VOSTROM",
        "VSL-1.0",
        "Vim",
        "Vixie-Cron",
        "W3C",
        "W3C-19980720",
        "W3C-20150513",
        "WTFNMFPL",
        "WTFPL",
        "Watcom-1.0",
        "Widget-Workshop",
        "WordNet",
        "Wsuipa",
        "X11",
        "X11-distribute-modifications-variant",
        "X11-no-permit-persons",
        "X11-swapped",
        "XFree86-1.1",
        "XSkat",
        "Xdebug-1.03",
        "Xerox",
        "Xfig",
        "Xnet",
        "YPL-1.0",
        "YPL-1.1",
        "ZPL-1.1",
        "ZPL-2.0",
        "ZPL-2.1",
        "Zed",
        "Zeeff",
        "Zend-2.0",
        "Zimbra-1.3",
        "Zimbra-1.4",
        "Zlib",
        "any-OSI",
        "any-OSI-perl-modules",
        "bcrypt-Solar-Designer",
        "blessing",
        "bzip2-1.0.5",
        "bzip2-1.0.6",
        "check-cvs",
        "checkmk",
        "copyleft-next-0.3.0",
        "copyleft-next-0.3.1",
        "curl",
        "cve-tou",
        "diffmark",
        "dtoa",
        "dvipdfm",
        "eCos-2.0",
        "eGenix",
        "etalab-2.0",
        "fwlw",
        "gSOAP-1.3b",
        "generic-xts",
        "gnuplot",
        "gtkbook",
        "hdparm",
        "hyphen-bulgarian",
        "iMatix",
        "jove",
        "libpng-1.6.35",
        "libpng-2.0",
        "libselinux-1.0",
        "libtiff",
        "libutil-David-Nugent",
        "lsof",
        "magaz",
        "mailprio",
        "man2html",
        "metamail",
        "mpi-permissive",
        "mpich2",
        "mplus",
        "ngrep",
        "pkgconf",
        "pnmstitch",
        "psfrag",
        "psutils",
        "python-ldap",
        "radvd",
        "snprintf",
        "softSurfer",
        "ssh-keyscan",
        "swrule",
        "threeparttable",
        "ulem",
        "w3m",
        "wwl",
        "wxWindows",
        "xinetd",
        "xkeyboard-config-Zinoviev",
        "xlock",
        "xpp",
        "xzoom",
        "zlib-acknowledgement",
    },
)

# Per-ID flags: (is_osi_approved, is_fsf_libre, is_deprecated).
# is_fsf_libre is None when upstream omits the field.
SPDX_LICENSE_FLAGS: dict[str, tuple[bool, bool | None, bool]] = {
    "0BSD": (True, None, False),
    "3D-Slicer-1.0": (False, None, False),
    "AAL": (True, None, False),
    "ADSL": (False, None, False),
    "AFL-1.1": (True, True, False),
    "AFL-1.2": (True, True, False),
    "AFL-2.0": (True, True, False),
    "AFL-2.1": (True, True, False),
    "AFL-3.0": (True, True, False),
    "AGPL-1.0": (False, True, True),
    "AGPL-1.0-only": (False, None, False),
    "AGPL-1.0-or-later": (False, None, False),
    "AGPL-3.0": (True, True, True),
    "AGPL-3.0-only": (True, True, False),
    "AGPL-3.0-or-later": (True, True, False),
    "ALGLIB-Documentation": (True, None, False),
    "AMD-newlib": (False, None, False),
    "AMDPLPA": (False, None, False),
    "AML": (False, None, False),
    "AML-glslang": (False, None, False),
    "AMPAS": (False, None, False),
    "ANTLR-PD": (False, None, False),
    "ANTLR-PD-fallback": (False, None, False),
    "APAFML": (False, None, False),
    "APL-1.0": (True, None, False),
    "APSL-1.0": (True, False, False),
    "APSL-1.1": (True, None, False),
    "APSL-1.2": (True, None, False),
    "APSL-2.0": (True, True, False),
    "ASWF-Digital-Assets-1.0": (False, None, False),
    "ASWF-Digital-Assets-1.1": (False, None, False),
    "Abstyles": (False, None, False),
    "AdaCore-doc": (False, None, False),
    "Adobe-2006": (False, None, False),
    "Adobe-Display-PostScript": (False, None, False),
    "Adobe-Glyph": (False, None, False),
    "Adobe-Utopia": (False, None, False),
    "Advanced-Cryptics-Dictionary": (False, None, False),
    "Afmparse": (False, None, False),
    "Aladdin": (False, False, False),
    "Apache-1.0": (False, True, False),
    "Apache-1.1": (True, True, False),
    "Apache-2.0": (True, True, False),
    "App-s2p": (False, None, False),
    "Arphic-1999": (False, None, False),
    "Artistic-1.0": (True, False, False),
    "Artistic-1.0-Perl": (True, None, False),
    "Artistic-1.0-cl8": (True, None, False),
    "Artistic-2.0": (True, True, False),
    "Artistic-dist": (False, None, False),
    "Aspell-RU": (False, None, False),
    "BOLA-1.1": (False, None, False),
    "BSD-1-Clause": (True, None, False),
    "BSD-2-Clause": (True, True, False),
    "BSD-2-Clause-Darwin": (False, None, False),
    "BSD-2-Clause-FreeBSD": (False, True, True),
    "BSD-2-Clause-NetBSD": (False, True, True),
    "BSD-2-Clause-Patent": (True, None, False),
    "BSD-2-Clause-Views": (False, None, False),
    "BSD-2-Clause-first-lines": (False, None, False),
    "BSD-2-Clause-pkgconf-disclaimer": (False, None, False),
    "BSD-3-Clause": (True, True, False),
    "BSD-3-Clause-Attribution": (False, None, False),
    "BSD-3-Clause-Clear": (False, True, False),
    "BSD-3-Clause-HP": (False, None, False),
    "BSD-3-Clause-LBNL": (True, None, False),
    "BSD-3-Clause-Modification": (False, None, False),
    "BSD-3-Clause-No-Military-License": (False, None, False),
    "BSD-3-Clause-No-Nuclear-License": (False, None, False),
    "BSD-3-Clause-No-Nuclear-License-2014": (False, None, False),
    "BSD-3-Clause-No-Nuclear-Warranty": (False, None, False),
    "BSD-3-Clause-Open-MPI": (True, None, False),
    "BSD-3-Clause-Sun": (False, None, False),
    "BSD-3-Clause-Tso": (False, None, False),
    "BSD-3-Clause-acpica": (False, None, False),
    "BSD-3-Clause-flex": (False, None, False),
    "BSD-4-Clause": (False, True, False),
    "BSD-4-Clause-Shortened": (False, None, False),
    "BSD-4-Clause-UC": (False, None, False),
    "BSD-4.3RENO": (False, None, False),
    "BSD-4.3TAHOE": (False, None, False),
    "BSD-Advertising-Acknowledgement": (False, None, False),
    "BSD-Attribution-HPND-disclaimer": (False, None, False),
    "BSD-Inferno-Nettverk": (False, None, False),
    "BSD-Mark-Modifications": (False, None, False),
    "BSD-Protection": (False, None, False),
    "BSD-Source-Code": (False, None, False),
    "BSD-Source-beginning-file": (False, None, False),
    "BSD-Systemics": (False, None, False),
    "BSD-Systemics-W3Works": (False, None, False),
    "BSL-1.0": (True, True, False),
    "BUSL-1.1": (False, None, False),
    "Baekmuk": (False, None, False),
    "Bahyph": (False, None, False),
    "Barr": (False, None, False),
    "Beerware": (False, None, False),
    "BitTorrent-1.0": (False, None, False),
    "BitTorrent-1.1": (False, True, False),
    "Bitstream-Charter": (False, None, False),
    "Bitstream-Vera": (False, None, False),
    "BlueOak-1.0.0": (True, None, False),
    "Boehm-GC": (False, None, False),
    "Boehm-GC-without-fee": (False, None, False),
    "Borceux": (False, None, False),
    "Brian-Gladman-2-Clause": (False, None, False),
    "Brian-Gladman-3-Clause": (False, None, False),
    "Buddy": (False, None, False),
    "C-UDA-1.0": (False, None, False),
    "CAL-1.0": (True, None, False),
    "CAL-1.0-Combined-Work-Exception": (True, None, False),
    "CAPEC-tou": (False, None, False),
    "CATOSL-1.1": (True, None, False),
    "CC-BY-1.0": (False, None, False),
    "CC-BY-2.0": (False, None, False),
    "CC-BY-2.5": (False, None, False),
    "CC-BY-2.5-AU": (False, None, False),
    "CC-BY-3.0": (False, None, False),
    "CC-BY-3.0-AT": (False, None, False),
    "CC-BY-3.0-AU": (False, None, False),
    "CC-BY-3.0-DE": (False, None, False),
    "CC-BY-3.0-IGO": (False, None, False),
    "CC-BY-3.0-NL": (False, None, False),
    "CC-BY-3.0-US": (False, None, False),
    "CC-BY-4.0": (False, True, False),
    "CC-BY-NC-1.0": (False, False, False),
    "CC-BY-NC-2.0": (False, False, False),
    "CC-BY-NC-2.5": (False, False, False),
    "CC-BY-NC-3.0": (False, False, False),
    "CC-BY-NC-3.0-DE": (False, None, False),
    "CC-BY-NC-4.0": (False, False, False),
    "CC-BY-NC-ND-1.0": (False, None, False),
    "CC-BY-NC-ND-2.0": (False, None, False),
    "CC-BY-NC-ND-2.5": (False, None, False),
    "CC-BY-NC-ND-3.0": (False, None, False),
    "CC-BY-NC-ND-3.0-DE": (False, None, False),
    "CC-BY-NC-ND-3.0-IGO": (False, None, False),
    "CC-BY-NC-ND-4.0": (False, None, False),
    "CC-BY-NC-SA-1.0": (False, None, False),
    "CC-BY-NC-SA-2.0": (False, None, False),
    "CC-BY-NC-SA-2.0-DE": (False, None, False),
    "CC-BY-NC-SA-2.0-FR": (False, None, False),
    "CC-BY-NC-SA-2.0-UK": (False, None, False),
    "CC-BY-NC-SA-2.5": (False, None, False),
    "CC-BY-NC-SA-3.0": (False, None, False),
    "CC-BY-NC-SA-3.0-DE": (False, None, False),
    "CC-BY-NC-SA-3.0-IGO": (False, None, False),
    "CC-BY-NC-SA-4.0": (False, None, False),
    "CC-BY-ND-1.0": (False, False, False),
    "CC-BY-ND-2.0": (False, False, False),
    "CC-BY-ND-2.5": (False, False, False),
    "CC-BY-ND-3.0": (False, False, False),
    "CC-BY-ND-3.0-DE": (False, None, False),
    "CC-BY-ND-4.0": (False, False, False),
    "CC-BY-SA-1.0": (False, None, False),
    "CC-BY-SA-2.0": (False, None, False),
    "CC-BY-SA-2.0-UK": (False, None, False),
    "CC-BY-SA-2.1-JP": (False, None, False),
    "CC-BY-SA-2.5": (False, None, False),
    "CC-BY-SA-3.0": (False, None, False),
    "CC-BY-SA-3.0-AT": (False, None, False),
    "CC-BY-SA-3.0-DE": (False, None, False),
    "CC-BY-SA-3.0-IGO": (False, None, False),
    "CC-BY-SA-4.0": (False, True, False),
    "CC-PDDC": (False, None, False),
    "CC-PDM-1.0": (False, None, False),
    "CC-SA-1.0": (False, None, False),
    "CC0-1.0": (False, True, False),
    "CDDL-1.0": (True, True, False),
    "CDDL-1.1": (False, None, False),
    "CDL-1.0": (False, None, False),
    "CDLA-Permissive-1.0": (False, None, False),
    "CDLA-Permissive-2.0": (False, None, False),
    "CDLA-Sharing-1.0": (False, None, False),
    "CECILL-1.0": (False, None, False),
    "CECILL-1.1": (False, None, False),
    "CECILL-2.0": (False, True, False),
    "CECILL-2.1": (True, None, False),
    "CECILL-B": (False, True, False),
    "CECILL-C": (False, True, False),
    "CERN-OHL-1.1": (False, None, False),
    "CERN-OHL-1.2": (False, None, False),
    "CERN-OHL-P-2.0": (True, None, False),
    "CERN-OHL-S-2.0": (True, None, False),
    "CERN-OHL-W-2.0": (True, None, False),
    "CFITSIO": (False, None, False),
    "CMU-Mach": (False, None, False),
    "CMU-Mach-nodoc": (False, None, False),
    "CNRI-Jython": (False, None, False),
    "CNRI-Python": (True, None, False),
    "CNRI-Python-GPL-Compatible": (False, None, False),
    "COIL-1.0": (False, None, False),
    "CPAL-1.0": (True, True, False),
    "CPL-1.0": (True, True, False),
    "CPOL-1.02": (False, False, False),
    "CUA-OPL-1.0": (True, None, False),
    "Caldera": (False, None, False),
    "Caldera-no-preamble": (False, None, False),
    "Catharon": (False, None, False),
    "ClArtistic": (False, True, False),
    "Clips": (False, None, False),
    "Community-Spec-1.0": (False, None, False),
    "Condor-1.1": (False, True, False),
    "Cornell-Lossless-JPEG": (False, None, False),
    "Cronyx": (False, None, False),
    "Crossword": (False, None, False),
    "CryptoSwift": (False, None, False),
    "CrystalStacker": (False, None, False),
    "Cube": (False, None, False),
    "D-FSL-1.0": (False, None, False),
    "DEC-3-Clause": (False, None, False),
    "DL-DE-BY-2.0": (False, None, False),
    "DL-DE-ZERO-2.0": (False, None, False),
    "DOC": (False, None, False),
    "DRL-1.0": (False, None, False),
    "DRL-1.1": (False, None, False),
    "DSDP": (False, None, False),
    "DocBook-DTD": (False, None, False),
    "DocBook-Schema": (False, None, False),
    "DocBook-Stylesheet": (False, None, False),
    "DocBook-XML": (False, None, False),
    "Dotseqn": (False, None, False),
    "ECL-1.0": (True, None, False),
    "ECL-2.0": (True, True, False),
    "EFL-1.0": (True, None, False),
    "EFL-2.0": (True, True, False),
    "EPICS": (False, None, False),
    "EPL-1.0": (True, True, False),
    "EPL-2.0": (True, True, False),
    "ESA-PL-permissive-2.4": (False, None, False),
    "ESA-PL-strong-copyleft-2.4": (False, None, False),
    "ESA-PL-weak-copyleft-2.4": (False, None, False),
    "EUDatagrid": (True, True, False),
    "EUPL-1.0": (False, None, False),
    "EUPL-1.1": (True, True, False),
    "EUPL-1.2": (True, True, False),
    "Elastic-2.0": (False, None, False),
    "Entessa": (True, None, False),
    "ErlPL-1.1": (False, None, False),
    "Eurosym": (False, None, False),
    "FBM": (False, None, False),
    "FDK-AAC": (False, None, False),
    "FSFAP": (False, True, False),
    "FSFAP-no-warranty-disclaimer": (False, None, False),
    "FSFUL": (False, None, False),
    "FSFULLR": (False, None, False),
    "FSFULLRSD": (False, None, False),
    "FSFULLRWD": (False, None, False),
    "FSL-1.1-ALv2": (False, None, False),
    "FSL-1.1-MIT": (False, None, False),
    "FTL": (False, True, False),
    "Fair": (True, None, False),
    "Ferguson-Twofish": (False, None, False),
    "Frameworx-1.0": (True, None, False),
    "FreeBSD-DOC": (False, None, False),
    "FreeImage": (False, None, False),
    "Furuseth": (False, None, False),
    "GCR-docs": (False, None, False),
    "GD": (False, None, False),
    "GFDL-1.1": (False, True, True),
    "GFDL-1.1-invariants-only": (False, None, False),
    "GFDL-1.1-invariants-or-later": (False, None, False),
    "GFDL-1.1-no-invariants-only": (False, None, False),
    "GFDL-1.1-no-invariants-or-later": (False, None, False),
    "GFDL-1.1-only": (False, True, False),
    "GFDL-1.1-or-later": (False, True, False),
    "GFDL-1.2": (False, True, True),
    "GFDL-1.2-invariants-only": (False, None, False),
    "GFDL-1.2-invariants-or-later": (False, None, False),
    "GFDL-1.2-no-invariants-only": (False, None, False),
    "GFDL-1.2-no-invariants-or-later": (False, None, False),
    "GFDL-1.2-only": (False, True, False),
    "GFDL-1.2-or-later": (False, True, False),
    "GFDL-1.3": (False, True, True),
    "GFDL-1.3-invariants-only": (False, None, False),
    "GFDL-1.3-invariants-or-later": (False, None, False),
    "GFDL-1.3-no-invariants-only": (False, None, False),
    "GFDL-1.3-no-invariants-or-later": (False, None, False),
    "GFDL-1.3-only": (False, True, False),
    "GFDL-1.3-or-later": (False, True, False),
    "GL2PS": (False, None, False),
    "GLWTPL": (False, None, False),
    "GPL-1.0": (False, None, True),
    "GPL-1.0+": (False, None, True),
    "GPL-1.0-only": (False, None, False),
    "GPL-1.0-or-later": (False, None, False),
    "GPL-2.0": (True, True, True),
    "GPL-2.0+": (True, True, True),
    "GPL-2.0-only": (True, True, False),
    "GPL-2.0-or-later": (True, True, False),
    "GPL-2.0-with-GCC-exception": (False, None, True),
    "GPL-2.0-with-autoconf-exception": (False, None, True),
    "GPL-2.0-with-bison-exception": (False, None, True),
    "GPL-2.0-with-classpath-exception": (False, None, True),
    "GPL-2.0-with-font-exception": (False, None, True),
    "GPL-3.0": (True, True, True),
    "GPL-3.0+": (True, True, True),
    "GPL-3.0-only": (True, True, False),
    "GPL-3.0-or-later": (True, True, False),
    "GPL-3.0-with-GCC-exception": (True, None, True),
    "GPL-3.0-with-autoconf-exception": (False, None, True),
    "Game-Programming-Gems": (False, None, False),
    "Giftware": (False, None, False),
    "Glide": (False, None, False),
    "Glulxe": (False, None, False),
    "Graphics-Gems": (False, None, False),
    "Gutmann": (False, None, False),
    "HDF5": (False, None, False),
    "HIDAPI": (False, None, False),
    "HP-1986": (False, None, False),
    "HP-1989": (False, None, False),
    "HPND": (True, True, False),
    "HPND-DEC": (False, None, False),
    "HPND-Fenneberg-Livingston": (False, None, False),
    "HPND-INRIA-IMAG": (False, None, False),
    "HPND-Intel": (False, None, False),
    "HPND-Kevlin-Henney": (False, None, False),
    "HPND-MIT-disclaimer": (False, None, False),
    "HPND-Markus-Kuhn": (False, None, False),
    "HPND-Netrek": (False, None, False),
    "HPND-Pbmplus": (False, None, False),
    "HPND-SMC": (False, None, False),
    "HPND-UC": (False, None, False),
    "HPND-UC-export-US": (False, None, False),
    "HPND-doc": (False, None, False),
    "HPND-doc-sell": (False, None, False),
    "HPND-export-US": (False, None, False),
    "HPND-export-US-acknowledgement": (False, None, False),
    "HPND-export-US-modify": (False, None, False),
    "HPND-export2-US": (False, None, False),
    "HPND-merchantability-variant": (False, None, False),
    "HPND-sell-MIT-disclaimer-xserver": (False, None, False),
    "HPND-sell-regexpr": (False, None, False),
    "HPND-sell-variant": (False, None, False),
    "HPND-sell-variant-MIT-disclaimer": (False, None, False),
    "HPND-sell-variant-MIT-disclaimer-rev": (False, None, False),
    "HPND-sell-variant-critical-systems": (False, None, False),
    "HTMLTIDY": (False, None, False),
    "HaskellReport": (False, None, False),
    "Hippocratic-2.1": (False, None, False),
    "IBM-pibs": (False, None, False),
    "ICU": (True, None, False),
    "IEC-Code-Components-EULA": (False, None, False),
    "IJG": (False, True, False),
    "IJG-short": (False, None, False),
    "IPA": (True, True, False),
    "IPL-1.0": (True, True, False),
    "ISC": (True, True, False),
    "ISC-Veillard": (False, None, False),
    "ISO-permission": (False, None, False),
    "ImageMagick": (False, None, False),
    "Imlib2": (False, True, False),
    "Info-ZIP": (False, None, False),
    "Inner-Net-2.0": (False, None, False),
    "InnoSetup": (False, None, False),
    "Intel": (True, True, False),
    "Intel-ACPI": (False, None, False),
    "Interbase-1.0": (False, None, False),
    "JPL-image": (False, None, False),
    "JPNIC": (False, None, False),
    "JSON": (False, False, False),
    "Jam": (True, None, False),
    "JasPer-2.0": (False, None, False),
    "Kastrup": (False, None, False),
    "Kazlib": (False, None, False),
    "Knuth-CTAN": (False, None, False),
    "LAL-1.2": (False, None, False),
    "LAL-1.3": (False, None, False),
    "LGPL-2.0": (True, None, True),
    "LGPL-2.0+": (True, None, True),
    "LGPL-2.0-only": (True, None, False),
    "LGPL-2.0-or-later": (True, None, False),
    "LGPL-2.1": (True, True, True),
    "LGPL-2.1+": (True, True, True),
    "LGPL-2.1-only": (True, True, False),
    "LGPL-2.1-or-later": (True, True, False),
    "LGPL-3.0": (True, True, True),
    "LGPL-3.0+": (True, True, True),
    "LGPL-3.0-only": (True, True, False),
    "LGPL-3.0-or-later": (True, True, False),
    "LGPLLR": (False, None, False),
    "LOOP": (False, None, False),
    "LPD-document": (False, None, False),
    "LPL-1.0": (True, None, False),
    "LPL-1.02": (True, True, False),
    "LPPL-1.0": (False, None, False),
    "LPPL-1.1": (False, None, False),
    "LPPL-1.2": (False, True, False),
    "LPPL-1.3a": (False, True, False),
    "LPPL-1.3c": (True, None, False),
    "LZMA-SDK-9.11-to-9.20": (False, None, False),
    "LZMA-SDK-9.22": (False, None, False),
    "Latex2e": (False, None, False),
    "Latex2e-translated-notice": (False, None, False),
    "Leptonica": (False, None, False),
    "LiLiQ-P-1.1": (True, None, False),
    "LiLiQ-R-1.1": (True, None, False),
    "LiLiQ-Rplus-1.1": (True, None, False),
    "Libpng": (False, None, False),
    "Linux-OpenIB": (False, None, False),
    "Linux-man-pages-1-para": (False, None, False),
    "Linux-man-pages-copyleft": (False, None, False),
    "Linux-man-pages-copyleft-2-para": (False, None, False),
    "Linux-man-pages-copyleft-var": (False, None, False),
    "Lucida-Bitmap-Fonts": (False, None, False),
    "MIPS": (False, None, False),
    "MIT": (True, True, False),
    "MIT-0": (True, None, False),
    "MIT-CMU": (False, None, False),
    "MIT-Click": (False, None, False),
    "MIT-Festival": (False, None, False),
    "MIT-Khronos-old": (False, None, False),
    "MIT-Modern-Variant": (True, None, False),
    "MIT-STK": (False, None, False),
    "MIT-Wu": (False, None, False),
    "MIT-advertising": (False, None, False),
    "MIT-enna": (False, None, False),
    "MIT-feh": (False, None, False),
    "MIT-open-group": (False, None, False),
    "MIT-testregex": (False, None, False),
    "MITNFA": (False, None, False),
    "MMIXware": (False, None, False),
    "MMPL-1.0.1": (False, None, False),
    "MPEG-SSG": (False, None, False),
    "MPL-1.0": (True, None, False),
    "MPL-1.1": (True, True, False),
    "MPL-2.0": (True, True, False),
    "MPL-2.0-no-copyleft-exception": (True, None, False),
    "MS-LPL": (False, None, False),
    "MS-PL": (True, True, False),
    "MS-RL": (True, True, False),
    "MTLL": (False, None, False),
    "Mackerras-3-Clause": (False, None, False),
    "Mackerras-3-Clause-acknowledgment": (False, None, False),
    "MakeIndex": (False, None, False),
    "Martin-Birgmeier": (False, None, False),
    "McPhee-slideshow": (False, None, False),
    "Minpack": (False, None, False),
    "MirOS": (True, None, False),
    "Motosoto": (True, None, False),
    "MulanPSL-1.0": (False, None, False),
    "MulanPSL-2.0": (True, None, False),
    "Multics": (True, None, False),
    "Mup": (False, None, False),
    "NAIST-2003": (False, None, False),
    "NASA-1.3": (True, False, False),
    "NBPL-1.0": (False, None, False),
    "NCBI-PD": (False, None, False),
    "NCGL-UK-2.0": (False, None, False),
    "NCL": (False, None, False),
    "NCSA": (True, True, False),
    "NGPL": (True, None, False),
    "NICTA-1.0": (False, None, False),
    "NIST-PD": (False, None, False),
    "NIST-PD-TNT": (False, None, False),
    "NIST-PD-fallback": (False, None, False),
    "NIST-Software": (False, None, False),
    "NLOD-1.0": (False, None, False),
    "NLOD-2.0": (False, None, False),
    "NLPL": (False, None, False),
    "NOSL": (False, True, False),
    "NPL-1.0": (False, True, False),
    "NPL-1.1": (False, True, False),
    "NPOSL-3.0": (True, None, False),
    "NRL": (False, None, False),
    "NTIA-PD": (False, None, False),
    "NTP": (True, None, False),
    "NTP-0": (False, None, False),
    "Naumen": (True, None, False),
    "Net-SNMP": (False, None, True),
    "NetCDF": (False, None, False),
    "Newsletr": (False, None, False),
    "Nokia": (True, True, False),
    "Noweb": (False, None, False),
    "Nunit": (False, True, True),
    "O-UDA-1.0": (False, None, False),
    "OAR": (False, None, False),
    "OCCT-PL": (False, None, False),
    "OCLC-2.0": (True, None, False),
    "ODC-By-1.0": (False, None, False),
    "ODbL-1.0": (False, True, False),
    "OFFIS": (False, None, False),
    "OFL-1.0": (False, True, False),
    "OFL-1.0-RFN": (False, None, False),
    "OFL-1.0-no-RFN": (False, None, False),
    "OFL-1.1": (True, True, False),
    "OFL-1.1-RFN": (True, None, False),
    "OFL-1.1-no-RFN": (True, None, False),
    "OGC-1.0": (False, None, False),
    "OGDL-Taiwan-1.0": (False, None, False),
    "OGL-Canada-2.0": (False, None, False),
    "OGL-UK-1.0": (False, None, False),
    "OGL-UK-2.0": (False, None, False),
    "OGL-UK-3.0": (False, None, False),
    "OGTSL": (True, None, False),
    "OLDAP-1.1": (False, None, False),
    "OLDAP-1.2": (False, None, False),
    "OLDAP-1.3": (False, None, False),
    "OLDAP-1.4": (False, None, False),
    "OLDAP-2.0": (False, None, False),
    "OLDAP-2.0.1": (False, None, False),
    "OLDAP-2.1": (False, None, False),
    "OLDAP-2.2": (False, None, False),
    "OLDAP-2.2.1": (False, None, False),
    "OLDAP-2.2.2": (False, None, False),
    "OLDAP-2.3": (False, True, False),
    "OLDAP-2.4": (False, None, False),
    "OLDAP-2.5": (False, None, False),
    "OLDAP-2.6": (False, None, False),
    "OLDAP-2.7": (False, True, False),
    "OLDAP-2.8": (True, None, False),
    "OLFL-1.3": (True, None, False),
    "OML": (False, None, False),
    "OPL-1.0": (False, False, False),
    "OPL-UK-3.0": (False, None, False),
    "OPUBL-1.0": (False, None, False),
    "OSC-1.0": (True, None, False),
    "OSET-PL-2.1": (True, None, False),
    "OSL-1.0": (True, True, False),
    "OSL-1.1": (False, True, False),
    "OSL-2.0": (True, True, False),
    "OSL-2.1": (True, True, False),
    "OSL-3.0": (True, True, False),
    "OSSP": (False, None, False),
    "OpenMDW-1.0": (False, None, False),
    "OpenPBS-2.3": (False, None, False),
    "OpenSSL": (False, True, False),
    "OpenSSL-standalone": (False, None, False),
    "OpenVision": (False, None, False),
    "PADL": (False, None, False),
    "PDDL-1.0": (False, None, False),
    "PHP-3.0": (True, None, False),
    "PHP-3.01": (True, True, False),
    "PPL": (False, False, False),
    "PSF-2.0": (False, None, False),
    "ParaType-Free-Font-1.3": (False, None, False),
    "Parity-6.0.0": (False, None, False),
    "Parity-7.0.0": (False, None, False),
    "Pixar": (False, None, False),
    "Plexus": (False, None, False),
    "PolyForm-Noncommercial-1.0.0": (False, None, False),
    "PolyForm-Small-Business-1.0.0": (False, None, False),
    "PostgreSQL": (True, None, False),
    "Python-2.0": (True, True, False),
    "Python-2.0.1": (False, None, False),
    "QPL-1.0": (True, True, False),
    "QPL-1.0-INRIA-2004": (False, None, False),
    "Qhull": (False, None, False),
    "RHeCos-1.1": (False, False, False),
    "RPL-1.1": (True, None, False),
    "RPL-1.5": (True, None, False),
    "RPSL-1.0": (True, True, False),
    "RSA-MD": (False, None, False),
    "RSCPL": (True, None, False),
    "Rdisc": (False, None, False),
    "Ruby": (False, True, False),
    "Ruby-pty": (False, None, False),
    "SAX-PD": (False, None, False),
    "SAX-PD-2.0": (False, None, False),
    "SCEA": (False, None, False),
    "SGI-B-1.0": (False, None, False),
    "SGI-B-1.1": (False, None, False),
    "SGI-B-2.0": (False, True, False),
    "SGI-OpenGL": (False, None, False),
    "SGMLUG-PM": (False, None, False),
    "SGP4": (False, None, False),
    "SHL-0.5": (False, None, False),
    "SHL-0.51": (False, None, False),
    "SISSL": (True, True, False),
    "SISSL-1.2": (False, None, False),
    "SL": (False, None, False),
    "SMAIL-GPL": (False, None, False),
    "SMLNJ": (False, True, False),
    "SMPPL": (False, None, False),
    "SNIA": (False, None, False),
    "SOFA": (False, None, False),
    "SPL-1.0": (True, True, False),
    "SSH-OpenSSH": (False, None, False),
    "SSH-short": (False, None, False),
    "SSLeay-standalone": (False, None, False),
    "SSPL-1.0": (False, None, False),
    "SUL-1.0": (False, None, False),
    "SWL": (False, None, False),
    "Saxpath": (False, None, False),
    "SchemeReport": (False, None, False),
    "Sendmail": (False, None, False),
    "Sendmail-8.23": (False, None, False),
    "Sendmail-Open-Source-1.1": (False, None, False),
    "SimPL-2.0": (True, None, False),
    "Sleepycat": (True, True, False),
    "Soundex": (False, None, False),
    "Spencer-86": (False, None, False),
    "Spencer-94": (False, None, False),
    "Spencer-99": (False, None, False),
    "StandardML-NJ": (False, True, True),
    "SugarCRM-1.1.3": (False, None, False),
    "Sun-PPP": (False, None, False),
    "Sun-PPP-2000": (False, None, False),
    "SunPro": (False, None, False),
    "Symlinks": (False, None, False),
    "TAPR-OHL-1.0": (False, None, False),
    "TCL": (False, None, False),
    "TCP-wrappers": (False, None, False),
    "TGPPL-1.0": (False, None, False),
    "TMate": (False, None, False),
    "TORQUE-1.1": (False, None, False),
    "TOSL": (False, None, False),
    "TPDL": (False, None, False),
    "TPL-1.0": (False, None, False),
    "TTWL": (False, None, False),
    "TTYP0": (False, None, False),
    "TU-Berlin-1.0": (False, None, False),
    "TU-Berlin-2.0": (False, None, False),
    "TekHVC": (False, None, False),
    "TermReadKey": (False, None, False),
    "ThirdEye": (False, None, False),
    "TrustedQSL": (False, None, False),
    "UCAR": (False, None, False),
    "UCL-1.0": (True, None, False),
    "UMich-Merit": (False, None, False),
    "UPL-1.0": (True, True, False),
    "URT-RLE": (False, None, False),
    "Ubuntu-font-1.0": (False, None, False),
    "UnRAR": (False, None, False),
    "Unicode-3.0": (True, None, False),
    "Unicode-DFS-2015": (False, None, False),
    "Unicode-DFS-2016": (True, None, False),
    "Unicode-TOU": (False, None, False),
    "UnixCrypt": (False, None, False),
    "Unlicense": (True, True, False),
    "Unlicense-libtelnet": (False, None, False),
    "Unlicense-libwhirlpool": (False, None, False),
    "VOSTROM": (False, None, False),
    "VSL-1.0": (True, None, False),
    "Vim": (False, True, False),
    "Vixie-Cron": (False, None, False),
    "W3C": (True, True, False),
    "W3C-19980720": (False, None, False),
    "W3C-20150513": (True, None, False),
    "WTFNMFPL": (False, None, False),
    "WTFPL": (False, True, False),
    "Watcom-1.0": (True, False, False),
    "Widget-Workshop": (False, None, False),
    "WordNet": (True, None, False),
    "Wsuipa": (False, None, False),
    "X11": (False, True, False),
    "X11-distribute-modifications-variant": (False, None, False),
    "X11-no-permit-persons": (False, None, False),
    "X11-swapped": (False, None, False),
    "XFree86-1.1": (False, True, False),
    "XSkat": (False, None, False),
    "Xdebug-1.03": (False, None, False),
    "Xerox": (False, None, False),
    "Xfig": (False, None, False),
    "Xnet": (True, None, False),
    "YPL-1.0": (False, None, False),
    "YPL-1.1": (False, True, False),
    "ZPL-1.1": (False, None, False),
    "ZPL-2.0": (True, True, False),
    "ZPL-2.1": (True, True, False),
    "Zed": (False, None, False),
    "Zeeff": (False, None, False),
    "Zend-2.0": (False, True, False),
    "Zimbra-1.3": (False, True, False),
    "Zimbra-1.4": (False, None, False),
    "Zlib": (True, True, False),
    "any-OSI": (False, None, False),
    "any-OSI-perl-modules": (False, None, False),
    "bcrypt-Solar-Designer": (False, None, False),
    "blessing": (False, None, False),
    "bzip2-1.0.5": (False, None, True),
    "bzip2-1.0.6": (False, None, False),
    "check-cvs": (False, None, False),
    "checkmk": (False, None, False),
    "copyleft-next-0.3.0": (False, None, False),
    "copyleft-next-0.3.1": (False, None, False),
    "curl": (False, None, False),
    "cve-tou": (False, None, False),
    "diffmark": (False, None, False),
    "dtoa": (False, None, False),
    "dvipdfm": (False, None, False),
    "eCos-2.0": (False, True, True),
    "eGenix": (False, None, False),
    "etalab-2.0": (False, None, False),
    "fwlw": (False, None, False),
    "gSOAP-1.3b": (False, None, False),
    "generic-xts": (False, None, False),
    "gnuplot": (False, True, False),
    "gtkbook": (False, None, False),
    "hdparm": (False, None, False),
    "hyphen-bulgarian": (False, None, False),
    "iMatix": (False, True, False),
    "jove": (False, None, False),
    "libpng-1.6.35": (False, None, False),
    "libpng-2.0": (False, None, False),
    "libselinux-1.0": (False, None, False),
    "libtiff": (False, None, False),
    "libutil-David-Nugent": (False, None, False),
    "lsof": (False, None, False),
    "magaz": (False, None, False),
    "mailprio": (False, None, False),
    "man2html": (False, None, False),
    "metamail": (False, None, False),
    "mpi-permissive": (False, None, False),
    "mpich2": (False, None, False),
    "mplus": (False, None, False),
    "ngrep": (False, None, False),
    "pkgconf": (False, None, False),
    "pnmstitch": (False, None, False),
    "psfrag": (False, None, False),
    "psutils": (False, None, False),
    "python-ldap": (False, None, False),
    "radvd": (False, None, False),
    "snprintf": (False, None, False),
    "softSurfer": (False, None, False),
    "ssh-keyscan": (False, None, False),
    "swrule": (False, None, False),
    "threeparttable": (False, None, False),
    "ulem": (False, None, False),
    "w3m": (False, None, False),
    "wwl": (False, None, False),
    "wxWindows": (True, None, True),
    "xinetd": (False, True, False),
    "xkeyboard-config-Zinoviev": (False, None, False),
    "xlock": (False, None, False),
    "xpp": (False, None, False),
    "xzoom": (False, None, False),
    "zlib-acknowledgement": (False, None, False),
}
