# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Publish - TestPyPI Staging

'on':
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-publish-pypi.yml@4676e2737994e31cae7c7ef17d10d5106ae1c25a # v0.23.1
    with:
      test-pypi: true
      update-homebrew: false
      python-version: '3.14'
      tooling-ref: '4676e2737994e31cae7c7ef17d10d5106ae1c25a' # v0.23.1
      egress-policy: block
      allowed-endpoints: >
        github.com:443
        api.github.com:443
        codeload.github.com:443
        release-assets.githubusercontent.com:443
        objects.githubusercontent.com:443
        github-releases.githubusercontent.com:443
        raw.githubusercontent.com:443
        uploads.github.com:443
        ghcr.io:443
        pkg-containers.githubusercontent.com:443
        astral.sh:443
        releases.astral.sh:443
        pypi.org:443
        files.pythonhosted.org:443
        test.pypi.org:443
        upload.test.pypi.org:443
        fulcio.sigstore.dev:443
        rekor.sigstore.dev:443
        tuf-repo-cdn.sigstore.dev:443
        oauth2.sigstore.dev:443
    permissions:
      contents: read
      id-token: write
      attestations: write
