# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Publish - TestPyPI Staging

'on':
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-publish-pypi.yml@dfd52172e5ee817cb1b1baf24895209c5e18d5ad # v0.19.0
    with:
      test-pypi: true
      update-homebrew: false
      python-version: '3.14'
      tooling-ref: 'dfd52172e5ee817cb1b1baf24895209c5e18d5ad' # v0.19.0
      egress-policy: block
      allowed-endpoints: >
        github.com:443
        api.github.com:443
        codeload.github.com:443
        release-assets.githubusercontent.com:443
        objects.githubusercontent.com:443
        pypi.org:443
        files.pythonhosted.org:443
        test.pypi.org:443
        upload.test.pypi.org:443
    permissions:
      contents: read
      id-token: write
      attestations: write
