# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Security - OpenSSF Scorecard Analysis

'on':
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecards:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-scorecards.yml@22a7c110415d75843c2c216f95ed47aaeb8e26fc
    with:
      egress-policy: block
      allowed-endpoints: >
        github.com:443
        api.github.com:443
        codeload.github.com:443
        release-assets.githubusercontent.com:443
        objects.githubusercontent.com:443
    permissions:
      contents: read
      security-events: write
      id-token: write
