# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Quality Check - Action Pinning Validation

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions: {}

concurrency:
  group: validate-action-pinning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-validate-action-pinning.yml@d8fff0c6025ddf39c1ae048c04c5a050c7729a6e # v0.62.0
    with:
      tooling-ref: 'd8fff0c6025ddf39c1ae048c04c5a050c7729a6e' # v0.62.0
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
