# SPDX-License-Identifier: MIT
# For license details, see the repository root LICENSE file.
---
name: Quality Check - Action Pinning Validation

'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions: {}

concurrency:
  group: validate-action-pinning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    # yamllint disable-line rule:line-length
    uses: lgtm-hq/lgtm-ci/.github/workflows/reusable-validate-action-pinning.yml@768a6b72f0a5346b5ecba3f4e13b90040472341c # v0.52.3
    with:
      tooling-ref: '768a6b72f0a5346b5ecba3f4e13b90040472341c' # v0.52.3
      egress-policy: block
      egress-preset: github-tooling
    permissions:
      contents: read
